sonar.projectKey=Medtronic-LABS_uhis_lf_mobile
sonar.projectName=UHIS LF Mobile
sonar.sources=lib
sonar.tests=test
sonar.exclusions=build/**,android/.gradle/**,ios/Pods/**,**/*.g.dart,**/*.freezed.dart
sonar.dart.lcov.reportPaths=coverage/lcov.info
