# -*- coding: utf-8 -*-
"""Best-effort Bangla draft translations for every English string that had
no existing Bangla in app_strings.dart, keyed by the EXACT English text
(matching scripts/extract_translations.py's output). Written for BRAC to
review and correct -- not a final, verified translation.

Conventions followed (matching the existing, already-correct translations
already in app_strings.dart):
  - Standard clinical abbreviations/codes/units are kept in Latin script
    (ANC, NCD, TB, EPI, IMCI, PNC, BMI, MUAC, HbA1c, BP, mmHg, mmol/L, kg,
    SAM, MAM, FINDRISC, CUSUM, EWMA, XP, SYS, DIA, wks) -- this mirrors how
    Bangladeshi frontline health materials (BRAC, DGHS) write these terms.
  - {name}-style interpolation placeholders are preserved verbatim, using
    the same real parameter name extract_translations.py assigns (not a
    generic {p0} token) so substitution works identically in both
    languages.
  - Internal/debug-only strings (AI Settings VAD tuning descriptions) are
    still translated for completeness, since BRAC can deprioritize them.
"""

MANUAL_BANGLA = {
    'LEAPWELL': 'LEAPWELL',
    'MedtronicLabs · Frontline Health': 'মেডট্রনিক ল্যাবস · ফ্রন্টলাইন হেলথ',
    'Powered by Medtronic Labs': 'মেডট্রনিক ল্যাবস দ্বারা পরিচালিত',
    'No internet connection. Use your PIN to continue working.': 'ইন্টারনেট সংযোগ নেই। কাজ চালিয়ে যেতে আপনার পিন ব্যবহার করুন।',
    'SHASTHYA KORMI': 'স্বাস্থ্য কর্মী',
    'Apon Sushashthya': 'আপন সুস্বাস্থ্য',
    'Refresh': 'রিফ্রেশ করুন',
    'English': 'English',
    'বাংলা (Bangla)': 'বাংলা (Bangla)',
    'AI Settings': 'এআই সেটিংস',
    'Realtime ASR — voice detection tuning': 'রিয়েলটাইম এএসআর — ভয়েস ডিটেকশন টিউনিং',
    'Voice activity gate (VAD)': 'ভয়েস অ্যাক্টিভিটি গেট (VAD)',
    'Controls which mic audio is worth sending to the server during a live scribe session — saves mobile data, since the CHW pays for their own connection. A gate that is too strict can silently drop real speech from a quiet speaker; too loose sends more silence than necessary. Changes apply to the next recording session.': 'লাইভ স্ক্রাইব সেশনে কোন মাইক অডিও সার্ভারে পাঠানো উপযুক্ত তা নিয়ন্ত্রণ করে — মোবাইল ডেটা সাশ্রয় করে, কারণ সিএইচডাব্লিউ নিজের সংযোগের খরচ বহন করেন। খুব কড়া গেট হলে আস্তে কথা বলা ব্যক্তির আসল কথা বাদ পড়তে পারে; খুব ঢিলা হলে প্রয়োজনের চেয়ে বেশি নীরবতা পাঠানো হয়। পরিবর্তন পরবর্তী রেকর্ডিং সেশনে কার্যকর হবে।',
    'Entry sensitivity': 'প্রবেশ সংবেদনশীলতা',
    "How many dB above the room's noise floor a sound must be to start being treated as speech. Lower = more sensitive to quiet speakers, but more likely to also pick up background noise.": 'রুমের শব্দের ভিত্তির (নয়েজ ফ্লোর) কত dB উপরে হলে একটি শব্দকে কথা হিসেবে ধরা হবে। কম মান = আস্তে কথা বলা ব্যক্তির জন্য বেশি সংবেদনশীল, কিন্তু পেছনের শব্দও ধরার সম্ভাবনা বেশি।',
    'Sustain sensitivity': 'স্থায়িত্ব সংবেদনশীলতা',
    "Lower bar used to *stay* in speech mode once started, so a natural dip in volume mid-sentence doesn't cut the recording. Should stay below entry sensitivity.": 'একবার কথা বলা শুরু হলে তা চালু রাখার জন্য কম মাত্রা ব্যবহার হয়, যাতে বাক্যের মাঝে স্বাভাবিক আওয়াজ কমে গেলেও রেকর্ডিং কেটে না যায়। এটি প্রবেশ সংবেদনশীলতার চেয়ে কম রাখা উচিত।',
    'Noise floor ceiling': 'নয়েজ ফ্লোর সর্বোচ্চ সীমা',
    'Caps how high the "background noise" estimate is allowed to climb in a loud room. Lower ceiling = easier for a quiet speaker to be heard over noisy surroundings.': 'শব্দময় ঘরে "পেছনের শব্দ" অনুমানকে কতটা উপরে উঠতে দেওয়া হবে তা সীমিত করে। কম সীমা = শব্দময় পরিবেশে আস্তে কথা বলা ব্যক্তিকেও শোনা সহজ হয়।',
    'Noise floor adaptation speed': 'নয়েজ ফ্লোর অভিযোজন গতি',
    'How quickly the background-noise estimate adjusts to the room. Higher = adapts faster to a changing environment.': 'পেছনের শব্দের অনুমান কত দ্রুত ঘরের সাথে সামঞ্জস্য করে। বেশি মান = পরিবর্তনশীল পরিবেশে দ্রুত মানিয়ে নেয়।',
    'Startup calibration window': 'শুরুর ক্যালিব্রেশন সময়',
    "How long at the very start of a recording is assumed silent, to measure the room's baseline noise. Longer reduces the risk of an immediate opening sentence skewing that baseline.": 'রেকর্ডিং শুরুতে কতক্ষণ নীরব ধরে নিয়ে ঘরের মৌলিক শব্দ মাপা হয়। বেশি সময় হলে শুরুর বাক্যে ভুল পরিমাপ হওয়ার ঝুঁকি কমে।',
    'Speech confirmation window': 'কথা নিশ্চিতকরণ সময়',
    "How long a sound must stay above the entry threshold before it's confirmed as real speech (filters out a single click or cough).": 'একটি শব্দকে আসল কথা হিসেবে নিশ্চিত করার আগে তা প্রবেশ সীমার উপরে কতক্ষণ থাকতে হবে (একক ক্লিক বা কাশি বাদ দেয়)।',
    'Trailing silence window': 'পরের নীরবতা সময়',
    'How long to keep recording after volume drops, to bridge a natural pause between words or sentences without cutting them apart.': 'শব্দ কমে যাওয়ার পরে কতক্ষণ রেকর্ডিং চালু রাখা হবে, যাতে শব্দ বা বাক্যের মধ্যে স্বাভাবিক বিরতি কাটা না পড়ে।',
    'Pre-speech buffer': 'কথা-পূর্ব বাফার',
    "How much audio just before speech is confirmed gets included anyway, so the very first word isn't clipped.": 'কথা নিশ্চিত হওয়ার ঠিক আগের কতটুকু অডিও অন্তর্ভুক্ত করা হবে, যাতে প্রথম শব্দটি কাটা না যায়।',
    'AI widgets': 'এআই উইজেট',
    "Turn off any AI-generated surface the SK doesn't want — each one still shows the equivalent local, rule-based content instead of nothing, and skips the network call, saving mobile data.": 'এসকে যে এআই-জেনারেটেড অংশ চান না তা বন্ধ করুন — প্রতিটির বদলে স্থানীয়, নিয়ম-ভিত্তিক তথ্য দেখানো হবে, নেটওয়ার্ক কল এড়িয়ে মোবাইল ডেটা সাশ্রয় হবে।',
    'Reset to default': 'ডিফল্টে ফিরুন',
    'Select all': 'সব নির্বাচন করুন',
    'Turn every AI widget below on or off at once.': 'নিচের সব এআই উইজেট একসাথে চালু বা বন্ধ করুন।',
    'Step 1 — Symptoms': 'ধাপ ১ — লক্ষণ',
    'Visit summary': 'ভিজিট সারাংশ',
    'The "Before You Knock" briefing cards shown before symptom entry.': 'লক্ষণ প্রবেশের আগে দেখানো "দরজায় যাওয়ার আগে" ব্রিফিং কার্ড।',
    'Voice symptom capture': 'ভয়েস লক্ষণ ক্যাপচার',
    'AI Scribe voice capture that pre-ticks symptom cards from what the SK says.': 'এসকে যা বলেন তা থেকে লক্ষণ কার্ড আগেই টিক দেয় এআই স্ক্রাইব ভয়েস ক্যাপচার।',
    'Step 2 — Assessment form': 'ধাপ ২ — মূল্যায়ন ফর্ম',
    'Voice form fill': 'ভয়েস ফর্ম পূরণ',
    'AI Scribe voice capture that fills in the vitals and clinical form fields.': 'ভাইটালস ও ক্লিনিকাল ফর্মের ঘর পূরণ করে এআই স্ক্রাইব ভয়েস ক্যাপচার।',
    'Step 3 — Recommendation': 'ধাপ ৩ — সুপারিশ',
    'Visit summary & recommendations': 'ভিজিট সারাংশ ও সুপারিশ',
    'The AI-generated visit summary, next actions, counselling, and follow-up plan.': 'এআই-তৈরি ভিজিট সারাংশ, পরবর্তী কাজ, কাউন্সেলিং ও ফলো-আপ পরিকল্পনা।',
    'Danger sign / referral alert': 'বিপদ চিহ্ন / রেফারেল সতর্কতা',
    'The alert card that flags danger signs and recommends a referral.': 'বিপদ চিহ্ন চিহ্নিত করে রেফারেলের সুপারিশ করা সতর্কতা কার্ড।',
    'WhatsApp draft': 'WhatsApp খসড়া',
    'The pre-written WhatsApp message summarising the visit for the patient.': 'রোগীর জন্য ভিজিটের সারাংশ সহ পূর্ব-লিখিত WhatsApp বার্তা।',
    'BMI': 'BMI',
    'MUAC': 'MUAC',
    'G/P': 'G/P',
    'NID / BRN': 'এনআইডি / জন্ম নিবন্ধন',
    'GPS': 'জিপিএস',
    '—': '—',
    'ANC': 'ANC',
    'IMCI': 'IMCI',
    'NCD': 'NCD',
    'TB': 'TB',
    'EPI': 'EPI',
    'Referral': 'রেফারেল',
    'ANC / MNCH': 'ANC / MNCH',
    'Triage': 'ট্রায়াজ',
    'patient': 'রোগী',
    'Visit not found. Please start a new visit.': 'ভিজিট পাওয়া যায়নি। নতুন ভিজিট শুরু করুন।',
    'Leave visit?': 'ভিজিট থেকে বের হবেন?',
    'Your progress will be saved. You can resume later.': 'আপনার অগ্রগতি সংরক্ষিত থাকবে। পরে চালিয়ে যেতে পারবেন।',
    'Stay': 'থাকুন',
    'Leave': 'বের হন',
    'How are you feeling?': 'আপনার কেমন লাগছে?',
    'AI triage': 'এআই ট্রায়াজ',
    'Detailed check': 'বিস্তারিত পরীক্ষা',
    'Before you knock · AI brief': 'দরজায় যাওয়ার আগে · এআই সংক্ষিপ্ত তথ্য',
    'SK ASKS THE FAMILY ': 'এসকে পরিবারকে জিজ্ঞাসা করেন ',
    'AI is checking — see what to do next': 'এআই যাচাই করছে — পরবর্তী কাজ দেখুন',
    'Record consultation': 'পরামর্শ রেকর্ড করুন',
    'Stop recording': 'রেকর্ডিং বন্ধ করুন',
    'Review AI note': 'এআই নোট পর্যালোচনা করুন',
    'Retry upload': 'আপলোড পুনরায় চেষ্টা করুন',
    'Recording…': 'রেকর্ড হচ্ছে…',
    'Uploading…': 'আপলোড হচ্ছে…',
    'AI processing note…': 'এআই নোট প্রসেস করছে…',
    'AI note ready — tap ✦ to review': 'এআই নোট প্রস্তুত — পর্যালোচনার জন্য ✦ চাপুন',
    'AI Scribe': 'এআই স্ক্রাইব',
    'Voice → clinical note': 'ভয়েস → ক্লিনিকাল নোট',
    'Allow': 'অনুমতি দিন',
    'Not now': 'এখন না',
    'Accept Note': 'নোট গ্রহণ করুন',
    'Reject': 'বাতিল করুন',
    'Review required': 'পর্যালোচনা প্রয়োজন',
    'Please review all sections before accepting.': 'গ্রহণ করার আগে সব বিভাগ পর্যালোচনা করুন।',
    'Note accepted ✓': 'নোট গৃহীত হয়েছে ✓',
    'Note discarded': 'নোট বাতিল করা হয়েছে',
    'Microphone access needed': 'মাইক্রোফোন অ্যাক্সেস প্রয়োজন',
    'AI Scribe needs microphone access to record consultations. Enable it in Settings → App permissions.': 'পরামর্শ রেকর্ড করতে এআই স্ক্রাইবের মাইক্রোফোন অ্যাক্সেস প্রয়োজন। সেটিংস → অ্যাপ পারমিশনে এটি চালু করুন।',
    'Open Settings': 'সেটিংস খুলুন',
    'Cancel': 'বাতিল',
    'Record conversation to auto-select symptoms?': 'লক্ষণ স্বয়ংক্রিয়ভাবে নির্বাচনের জন্য কথোপকথন রেকর্ড করবেন?',
    'Transcription failed.': 'ট্রান্সক্রিপশন ব্যর্থ হয়েছে।',
    'AI is taking too long. Tap to try again.': 'এআই বেশি সময় নিচ্ছে। আবার চেষ্টা করতে চাপুন।',
    'Could not reach AI Scribe. Tap to try again.': 'এআই স্ক্রাইবে পৌঁছানো যায়নি। আবার চেষ্টা করতে চাপুন।',
    'Recording could not be saved. Please record again.': 'রেকর্ডিং সংরক্ষণ করা যায়নি। আবার রেকর্ড করুন।',
    'Recording produced no output. Please record again.': 'রেকর্ডিং থেকে কোনো ফলাফল আসেনি। আবার রেকর্ড করুন।',
    'No speech detected — please speak closer to the microphone and try again.': 'কোনো কথা সনাক্ত হয়নি — মাইক্রোফোনের কাছে কথা বলে আবার চেষ্টা করুন।',
    'Could not start recording. Check microphone permissions and try again.': 'রেকর্ডিং শুরু করা যায়নি। মাইক্রোফোন পারমিশন যাচাই করে আবার চেষ্টা করুন।',
    '🎙 AI Scribe — tap and let him/her speak': '🎙 এআই স্ক্রাইব — চাপুন এবং তাকে কথা বলতে দিন',
    'Tap a mode to start': 'শুরু করতে একটি মোড চাপুন',
    'AI note ready — tap to review': 'এআই নোট প্রস্তুত — পর্যালোচনার জন্য চাপুন',
    'Upload failed — tap to retry': 'আপলোড ব্যর্থ — পুনরায় চেষ্টার জন্য চাপুন',
    'ASR': 'ASR',
    'Other': 'অন্যান্য',
    'OTHER': 'অন্যান্য',
    'Gemini': 'Gemini',
    'AI Scribe · Gemini': 'এআই স্ক্রাইব · Gemini',
    'Live ASR · Sarvam': 'লাইভ ASR · Sarvam',
    'AI Scribe mode': 'এআই স্ক্রাইব মোড',
    'AI Scribe (Gemini)': 'এআই স্ক্রাইব (Gemini)',
    'Records full consultation. AI analyzes after recording ends.': 'সম্পূর্ণ পরামর্শ রেকর্ড করে। রেকর্ডিং শেষে এআই বিশ্লেষণ করে।',
    'Live ASR (Sarvam)': 'লাইভ ASR (Sarvam)',
    'Real-time Bengali transcript + live detected symptoms.': 'রিয়েল-টাইম বাংলা ট্রান্সক্রিপ্ট + সরাসরি সনাক্ত হওয়া লক্ষণ।',
    'Default': 'ডিফল্ট',
    'What symptoms does the patient have?': 'রোগীর কী লক্ষণ আছে?',
    'Select all that apply': 'প্রযোজ্য সব নির্বাচন করুন',
    'No symptoms / routine visit': 'কোনো লক্ষণ নেই / নিয়মিত ভিজিট',
    'Continue': 'চালিয়ে যান',
    'Skip': 'এড়িয়ে যান',
    'Retry': 'পুনরায় চেষ্টা করুন',
    'Danger Signs': 'বিপদ চিহ্ন',
    'Fever & Respiratory': 'জ্বর ও শ্বাসযন্ত্র',
    'GI & Nutrition': 'পরিপাক ও পুষ্টি',
    'Maternal': 'মাতৃত্ব',
    'NCD / Metabolic': 'NCD / বিপাকীয়',
    'TB Indicators': 'যক্ষ্মার লক্ষণ',
    'Mental Health': 'মানসিক স্বাস্থ্য',
    'Child Health': 'শিশু স্বাস্থ্য',
    'Heavy bleeding': 'অতিরিক্ত রক্তক্ষরণ',
    'Foul-smelling vaginal discharge': 'দুর্গন্ধযুক্ত যোনি স্রাব',
    'Epigastric pain': 'উপরের পেটে ব্যথা',
    'Headache': 'মাথাব্যথা',
    'Edema': 'ফোলা (ইডিমা)',
    'Breast pain': 'স্তনে ব্যথা',
    'Breast swelling': 'স্তন ফোলা',
    'Perineal wound discharge': 'পেরিনিয়াল ক্ষত থেকে স্রাব',
    'Painful urination': 'প্রস্রাবে ব্যথা',
    'Breathlessness': 'শ্বাসকষ্ট',
    'Leaking fluids': 'পানি/তরল ঝরা',
    'Painful uterine contractions': 'জরায়ু সংকোচনে ব্যথা',
    'One-sided weakness': 'একপাশে দুর্বলতা',
    'Swelling of both feet': 'দুই পায়ে ফোলা',
    'Palpitations': 'বুক ধড়ফড়',
    'Swelling of one leg': 'এক পায়ে ফোলা',
    'Excessive thirst': 'অতিরিক্ত তৃষ্ণা',
    'Foot numbness': 'পায়ে অবশভাব',
    'Weakness': 'দুর্বলতা',
    '✦ Eligible services': '✦ উপযুক্ত সেবা',
    'Age & gender based': 'বয়স ও লিঙ্গ ভিত্তিক',
    'Enrolled': 'নিবন্ধিত',
    "⚠ Select 'PW' first to unlock ANC": "⚠ ANC আনলক করতে আগে 'PW' নির্বাচন করুন",
    'Temperature': 'তাপমাত্রা',
    'Respiratory rate': 'শ্বাসের হার',
    'Weight (kg)': 'ওজন (কেজি)',
    'MUAC (cm)': 'MUAC (সেমি)',
    'SpO2 (%)': 'SpO2 (%)',
    'Has cough': 'কাশি আছে',
    'Cough duration (days)': 'কাশির স্থিতিকাল (দিন)',
    'Has fever': 'জ্বর আছে',
    'Fever duration (days)': 'জ্বরের স্থিতিকাল (দিন)',
    'Has diarrhea': 'ডায়রিয়া আছে',
    'Unable to drink / breastfeed': 'পান করতে / বুকের দুধ খেতে অক্ষম',
    'Vomits everything': 'সবকিছু বমি করে ফেলে',
    'Has convulsions': 'খিঁচুনি আছে',
    'Lethargic / unconscious': 'অলস / অজ্ঞান',
    'Chest in-drawing': 'বুক ভেতরে টেনে যাওয়া',
    'Stridor when calm': 'শান্ত থাকলেও শব্দ করে শ্বাস',
    'Bloody diarrhea': 'রক্তমিশ্রিত ডায়রিয়া',
    'Fast breathing': 'দ্রুত শ্বাস',
    'RDT result': 'RDT ফলাফল',
    'ACT dispensed': 'ACT সরবরাহ করা হয়েছে',
    'ORS dispensed': 'ORS সরবরাহ করা হয়েছে',
    'Zinc dispensed': 'জিংক সরবরাহ করা হয়েছে',
    'Amoxicillin dispensed': 'অ্যামোক্সিসিলিন সরবরাহ করা হয়েছে',
    'Cough ≥ 2 weeks': 'কাশি ≥ ২ সপ্তাহ',
    'Night sweats': 'রাতে ঘাম',
    'Weight loss': 'ওজন কমে যাওয়া',
    'Relationship to index case': 'মূল রোগীর সাথে সম্পর্ক',
    'Sleep location': 'ঘুমানোর স্থান',
    'Previously treated for TB': 'পূর্বে যক্ষ্মার চিকিৎসা হয়েছে',
    'Height (cm)': 'উচ্চতা (সেমি)',
    'Pulse': 'পালস',
    'Systolic BP': 'সিস্টোলিক BP',
    'Diastolic BP': 'ডায়াস্টোলিক BP',
    'Weight': 'ওজন',
    'Fundal height': 'ফান্ডাল উচ্চতা',
    'Fetal heart rate': 'ভ্রূণের হৃদস্পন্দন',
    'Fetal movement': 'ভ্রূণের নড়াচড়া',
    'Oedema': 'ইডিমা (ফোলা)',
    'Pallor': 'রক্তাল্পতার লক্ষণ (পালোর)',
    'TT/Td vaccination': 'TT/Td টিকা',
    'IFA tablets provided': 'IFA ট্যাবলেট সরবরাহ করা হয়েছে',
    'Calcium tablets provided': 'ক্যালসিয়াম ট্যাবলেট সরবরাহ করা হয়েছে',
    'Facility identified for delivery': 'প্রসবের জন্য নির্ধারিত হাসপাতাল/ক্লিনিক',
    'Ultrasound': 'আল্ট্রাসাউন্ড',
    'Hemoglobin (Hb)': 'হিমোগ্লোবিন (Hb)',
    'Blood sugar type': 'রক্তে শর্করার ধরন',
    'Fasting blood sugar': 'খালি পেটের রক্তে শর্করা',
    'Random blood sugar': 'র\u200d্যান্ডম রক্তে শর্করা',
    'Urinary albumin': 'প্রস্রাবে অ্যালবুমিন',
    'Urinary sugar': 'প্রস্রাবে শর্করা',
    'Urinary bilirubin': 'প্রস্রাবে বিলিরুবিন',
    'Folic acid consumed (last month)': 'ফলিক অ্যাসিড সেবন (গত মাসে)',
    'Folic acid provided': 'ফলিক অ্যাসিড সরবরাহ করা হয়েছে',
    'IFA tablets consumed (last month)': 'IFA ট্যাবলেট সেবন (গত মাসে)',
    'Calcium consumed (last month)': 'ক্যালসিয়াম সেবন (গত মাসে)',
    'ANC visits with other providers': 'অন্য প্রদানকারীর কাছে ANC ভিজিট',
    'ANC from medical doctor?': 'চিকিৎসকের কাছ থেকে ANC নেওয়া হয়েছে?',
    'Previous pregnancy complications': 'পূর্ববর্তী গর্ভধারণে জটিলতা',
    'Danger signs (weeks 1–12)': 'বিপদ চিহ্ন (সপ্তাহ ১–১২)',
    'Danger signs (weeks 13–27)': 'বিপদ চিহ্ন (সপ্তাহ ১৩–২৭)',
    'Danger signs (weeks 28–40)': 'বিপদ চিহ্ন (সপ্তাহ ২৮–৪০)',
    'Referral facility': 'রেফারেল প্রতিষ্ঠান',
    'Systolic BP (2nd reading)': 'সিস্টোলিক BP (২য় পাঠ)',
    'Diastolic BP (2nd reading)': 'ডায়াস্টোলিক BP (২য় পাঠ)',
    'Regular smoker': 'নিয়মিত ধূমপায়ী',
    'Medication adherence': 'ওষুধ সেবনে নিয়মিততা',
    'Symptoms': 'লক্ষণ',
    'Had symptoms since last follow-up?': 'গত ফলো-আপের পর কোনো লক্ষণ ছিল?',
    'New or worsening symptoms': 'নতুন বা বেড়ে যাওয়া লক্ষণ',
    'Taking medication regularly?': 'নিয়মিত ওষুধ সেবন করছেন?',
    'Blood glucose': 'রক্তে গ্লুকোজ',
    'Glucose measurement type': 'গ্লুকোজ পরিমাপের ধরন',
    'HbA1c': 'HbA1c',
    'Foot examination': 'পায়ের পরীক্ষা',
    'Foot wound present': 'পায়ে ক্ষত আছে',
    'Morning headaches?': 'সকালে মাথাব্যথা?',
    'Chest tightness or shortness of breath?': 'বুকে চাপ বা শ্বাসকষ্ট?',
    'High salt in daily food?': 'দৈনিক খাবারে অতিরিক্ত লবণ?',
    'Family history of high BP?': 'পরিবারে উচ্চ রক্তচাপের ইতিহাস?',
    'One-sided weakness or stroke signs?': 'একপাশে দুর্বলতা বা স্ট্রোকের লক্ষণ?',
    'On BP medication?': 'রক্তচাপের ওষুধ সেবন করছেন?',
    'Waist circumference (cm)': 'কোমরের পরিধি (সেমি)',
    'Physically active ≥ 30 min/day?': 'প্রতিদিন ≥ ৩০ মিনিট শারীরিকভাবে সক্রিয়?',
    'Eats fruit / vegetables daily?': 'প্রতিদিন ফল/সবজি খান?',
    'Previous high blood glucose?': 'পূর্বে উচ্চ রক্তে গ্লুকোজ ছিল?',
    'Family history of diabetes?': 'পরিবারে ডায়াবেটিসের ইতিহাস?',
    'Number of living children': 'জীবিত সন্তানের সংখ্যা',
    'Age of last child (months)': 'শেষ সন্তানের বয়স (মাস)',
    'Desire for future children': 'ভবিষ্যতে সন্তান নেওয়ার ইচ্ছা',
    'Current FP method': 'বর্তমান পরিবার পরিকল্পনা পদ্ধতি',
    'Eye disease type(s)': 'চোখের রোগের ধরন',
    'Referred for operation?': 'অপারেশনের জন্য রেফার করা হয়েছে?',
    'NCD service provided?': 'NCD সেবা প্রদান করা হয়েছে?',
    'Eye test outcome': 'চোখ পরীক্ষার ফলাফল',
    'Glasses prescription': 'চশমার প্রেসক্রিপশন',
    'Glasses sold?': 'চশমা বিক্রি হয়েছে?',
    'General checks': 'সাধারণ পরীক্ষা',
    'NCD checks': 'NCD পরীক্ষা',
    'TB checks': 'যক্ষ্মা পরীক্ষা',
    'Antenatal checks': 'প্রসবপূর্ব পরীক্ষা',
    'Postnatal checks': 'প্রসবোত্তর পরীক্ষা',
    'Child health checks': 'শিশু স্বাস্থ্য পরীক্ষা',
    'Immunization': 'টিকাদান',
    'Nutrition': 'পুষ্টি',
    'Family planning': 'পরিবার পরিকল্পনা',
    'Cataract / eye disease': 'ছানি / চোখের রোগ',
    'Eye care': 'চক্ষু সেবা',
    'Overdue vaccines': 'বাকি থাকা টিকা',
    'Vaccines given today': 'আজ দেওয়া টিকা',
    'Edema of both feet': 'দুই পায়ে ফোলা',
    'Visible wasting': 'দৃশ্যমান শীর্ণতা',
    'Feeding difficulty': 'খাওয়ানোতে সমস্যা',
    'Supplementary food given': 'সম্পূরক খাবার দেওয়া হয়েছে',
    'Referred for SAM': 'SAM-এর জন্য রেফার করা হয়েছে',
    'Days post-delivery': 'প্রসবের পর দিন সংখ্যা',
    'Uterine pain': 'জরায়ুতে ব্যথা',
    'Excessive bleeding': 'অতিরিক্ত রক্তক্ষরণ',
    'Breast problem': 'স্তনের সমস্যা',
    'Newborn present': 'নবজাতক উপস্থিত',
    'Newborn breastfeeding': 'নবজাতক বুকের দুধ খাচ্ছে',
    'PNC vitamins given': 'PNC ভিটামিন দেওয়া হয়েছে',
    'Gravida': 'গ্র্যাভিডা (মোট গর্ভধারণ)',
    'Parity (total births)': 'প্যারিটি (মোট জন্ম)',
    'Living children': 'জীবিত সন্তান',
    'Known HTN patient?': 'পরিচিত উচ্চ রক্তচাপের রোগী?',
    'Pre-eclampsia / eclampsia?': 'প্রি-এক্লাম্পসিয়া / এক্লাম্পসিয়া?',
    'On treatment for HTN / eclampsia?': 'উচ্চ রক্তচাপ/এক্লাম্পসিয়ার চিকিৎসা চলছে?',
    'Known DM patient?': 'পরিচিত ডায়াবেটিস রোগী?',
    'Known GDM patient?': 'পরিচিত গর্ভকালীন ডায়াবেটিস রোগী?',
    'On treatment for DM / GDM?': 'ডায়াবেটিস/গর্ভকালীন ডায়াবেটিসের চিকিৎসা চলছে?',
    'Fasting blood sugar (mmol/L)': 'খালি পেটের রক্তে শর্করা (mmol/L)',
    'Random blood sugar (mmol/L)': 'র\u200d্যান্ডম রক্তে শর্করা (mmol/L)',
    'Postpartum danger signs': 'প্রসবোত্তর বিপদ চিহ্ন',
    'Vitamin A capsule consumed?': 'ভিটামিন এ ক্যাপসুল সেবন করা হয়েছে?',
    'IFA tablets consumed': 'IFA ট্যাবলেট সেবন করা হয়েছে',
    'Calcium tablets consumed': 'ক্যালসিয়াম ট্যাবলেট সেবন করা হয়েছে',
    'Family planning method': 'পরিবার পরিকল্পনা পদ্ধতি',
    'Newborn danger signs': 'নবজাতকের বিপদ চিহ্ন',
    'Other newborn signs': 'নবজাতকের অন্যান্য লক্ষণ',
    'Newborn referred to SBCU?': 'নবজাতক SBCU-তে রেফার করা হয়েছে?',
    'Low birth weight?': 'জন্মের সময় কম ওজন?',
    'Death of newborn?': 'নবজাতকের মৃত্যু হয়েছে?',
    'Congenital defect?': 'জন্মগত সমস্যা আছে?',
    'Child weight (kg)': 'শিশুর ওজন (কেজি)',
    'Child feeding in last 24 hours': 'গত ২৪ ঘণ্টায় শিশুর খাওয়ানো',
    'Other feed': 'অন্য খাবার',
    'Hours after birth breastfeeding started': 'জন্মের কত ঘণ্টা পর বুকের দুধ শুরু হয়েছে',
    'Month additional food started': 'কোন মাসে বাড়তি খাবার শুরু হয়েছে',
    'Child breastfeeding?': 'শিশু বুকের দুধ খায়?',
    'Additional food in last 24 hours?': 'গত ২৪ ঘণ্টায় বাড়তি খাবার দেওয়া হয়েছে?',
    'Child received vaccines?': 'শিশু টিকা পেয়েছে?',
    'Child took deworming medicine?': 'শিশু কৃমিনাশক ওষুধ খেয়েছে?',
    'Any illness / complications?': 'কোনো অসুস্থতা / জটিলতা আছে?',
    'Type of illness / complication': 'অসুস্থতা/জটিলতার ধরন',
    'Referral made?': 'রেফার করা হয়েছে?',
    'Referral facility type': 'রেফারেল প্রতিষ্ঠানের ধরন',
    'Vitals': 'ভাইটালস',
    'ICCM Assessment': 'ICCM মূল্যায়ন',
    'TB Screening': 'যক্ষ্মা স্ক্রিনিং',
    'ANC Vitals': 'ANC ভাইটালস',
    'ANC Assessment': 'ANC মূল্যায়ন',
    'Hypertension': 'উচ্চ রক্তচাপ',
    'Diabetes': 'ডায়াবেটিস',
    'EPI / Immunization': 'EPI / টিকাদান',
    'Nutrition Assessment': 'পুষ্টি মূল্যায়ন',
    'Postnatal Check': 'প্রসবোত্তর পরীক্ষা',
    'Postnatal — Mother': 'প্রসবোত্তর — মা',
    'Postnatal — Newborn': 'প্রসবোত্তর — নবজাতক',
    'Postnatal — Child': 'প্রসবোত্তর — শিশু',
    'Diabetes Risk (FINDRISC)': 'ডায়াবেটিস ঝুঁকি (FINDRISC)',
    'Family Planning': 'পরিবার পরিকল্পনা',
    'Cataract / Eye Disease': 'ছানি / চোখের রোগ',
    'Eye Care': 'চক্ষু সেবা',
    'Also mentioned': 'আরও উল্লেখ করা হয়েছে',
    'AI': 'এআই',
    'Pre-filled by AI — please verify': 'এআই দ্বারা পূরণ করা — যাচাই করুন',
    'Record': 'রেকর্ড',
    'TB screening added — cough ≥ 2 weeks': 'যক্ষ্মা স্ক্রিনিং যুক্ত করা হয়েছে — কাশি ≥ ২ সপ্তাহ',
    'Submit Assessment': 'মূল্যায়ন জমা দিন',
    'Resume visit?': 'ভিজিট চালিয়ে যাবেন?',
    'An unfinished assessment was found.': 'একটি অসম্পূর্ণ মূল্যায়ন পাওয়া গেছে।',
    'Resume': 'চালিয়ে যান',
    'Discard': 'বাতিল করুন',
    'Start Over': 'নতুন করে শুরু করুন',
    'Offline — showing basic guidance. Connect to internet for the full AI recommendation.': 'অফলাইন — মৌলিক পরামর্শ দেখানো হচ্ছে। সম্পূর্ণ এআই সুপারিশের জন্য ইন্টারনেটে সংযুক্ত হন।',
    'Next': 'পরবর্তী',
    'OK': 'ঠিক আছে',
    'Select date': 'তারিখ নির্বাচন করুন',
    'SYS': 'SYS',
    'DIA': 'DIA',
    'mmHg': 'mmHg',
    'Enter a valid reading': 'সঠিক পাঠ লিখুন',
    'Diastolic must be less than systolic': 'ডায়াস্টোলিক সিস্টোলিকের চেয়ে কম হতে হবে',
    'Enter a pulse between 50 and 300 bpm': '৫০ থেকে ৩০০ bpm-এর মধ্যে পালস লিখুন',
    'Enter a glucose reading between 1.0 and 15.0 mmol/L': '১.০ থেকে ১৫.০ mmol/L-এর মধ্যে গ্লুকোজ পাঠ লিখুন',
    'Enter a Hb reading between 1.0 and 20.0 g/dL': '১.০ থেকে ২০.০ g/dL-এর মধ্যে Hb পাঠ লিখুন',
    'Enter a temperature between 90 and 110°F, or 0 if it could not be measured': '৯০ থেকে ১১০°F-এর মধ্যে তাপমাত্রা লিখুন, অথবা মাপা না গেলে ০ লিখুন',
    'Enter a fundal height between 8 and 45 cm': '৮ থেকে ৪৫ সেমি-এর মধ্যে ফান্ডাল উচ্চতা লিখুন',
    'Enter an HbA1c reading between 4.0% and 14.0%': '৪.০% থেকে ১৪.০%-এর মধ্যে HbA1c পাঠ লিখুন',
    'Age': 'বয়স',
    'Date of Birth': 'জন্ম তারিখ',
    'Y': 'বছর',
    'M': 'মাস',
    'D': 'দিন',
    'None selected': 'কিছু নির্বাচন করা হয়নি',
    'Tap to select': 'নির্বাচন করতে চাপুন',
    'Done': 'সম্পন্ন',
    'Normal': 'স্বাভাবিক',
    'Elevated': 'বেড়ে গেছে',
    'Slightly elevated': 'একটু বেড়ে গেছে',
    'Stage 2 HTN': 'স্টেজ ২ উচ্চ রক্তচাপ',
    'Hypertensive Crisis ⚠': 'উচ্চ রক্তচাপ সংকট ⚠',
    'In Range': 'স্বাভাবিক সীমায়',
    'Out of Range': 'সীমার বাইরে',
    'High ⚠': 'বেশি ⚠',
    'Low ⚠': 'কম ⚠',
    'SAM': 'SAM',
    'MAM': 'MAM',
    'Ref:': 'রেফ:',
    'Urgency': 'জরুরিত্ব',
    'Routine': 'নিয়মিত',
    'Urgent': 'জরুরি',
    'Emergency': 'অত্যন্ত জরুরি',
    'Last Menstrual Period': 'সর্বশেষ মাসিক তারিখ',
    'Estimated Due Date': 'প্রত্যাশিত প্রসব তারিখ',
    'Gestational Age': 'গর্ভকালীন বয়স',
    'wks': 'সপ্তাহ',
    'days': 'দিন',
    'Preterm (< 37 weeks)': 'অকাল প্রসব (< ৩৭ সপ্তাহ)',
    'Pregnancy data not available': 'গর্ভাবস্থার তথ্য নেই',
    'LMP': 'LMP',
    'EDD': 'EDD',
    'OD (Right)': 'OD (ডান)',
    'OS (Left)': 'OS (বাম)',
    'Sphere': 'স্ফিয়ার',
    'Cylinder': 'সিলিন্ডার',
    'Axis': 'অক্ষ',
    'Prescription recorded': 'প্রেসক্রিপশন রেকর্ড করা হয়েছে',
    'ANC VISIT': 'ANC ভিজিট',
    'wks GA': 'সপ্তাহ গর্ভকালীন বয়স',
    '#': '#',
    'High-risk': 'উচ্চ-ঝুঁকি',
    'Near-term': 'প্রসবের কাছাকাছি',
    'ANC gap': 'ANC ব্যবধান',
    'BP elevated': 'রক্তচাপ বেড়ে গেছে',
    'G{g}P{p}': 'G{g}P{p}',
    'G{p0}P{p1}': 'G{p0}P{p1}',
    'Height': 'উচ্চতা',
    'Parity': 'প্যারিটি',
    'Living': 'জীবিত',
    'Albumin': 'অ্যালবুমিন',
    'Sugar': 'শর্করা',
    'Bilirubin': 'বিলিরুবিন',
    'Consumed': 'সেবিত',
    'Provided today': 'আজ প্রদান করা হয়েছে',
    'Refer now': 'এখনই রেফার করুন',
    'Add to assessment': 'মূল্যায়নে যুক্ত করুন',
    'Dismiss': 'বাতিল করুন',
    'Severe hypertension detected — refer immediately': 'তীব্র উচ্চ রক্তচাপ সনাক্ত — এখনই রেফার করুন',
    'High BP — add NCD hypertension assessment': 'উচ্চ রক্তচাপ — NCD উচ্চ রক্তচাপ মূল্যায়ন যুক্ত করুন',
    'Danger sign present — refer immediately': 'বিপদ চিহ্ন উপস্থিত — এখনই রেফার করুন',
    'Severe pneumonia — refer immediately': 'তীব্র নিউমোনিয়া — এখনই রেফার করুন',
    'Pneumonia — treat or refer if worsening': 'নিউমোনিয়া — চিকিৎসা করুন বা বাড়লে রেফার করুন',
    'Severe acute malnutrition — refer immediately': 'তীব্র অপুষ্টি — এখনই রেফার করুন',
    'Moderate malnutrition — treat at community': 'মাঝারি অপুষ্টি — কমিউনিটিতে চিকিৎসা করুন',
    'Severe anemia — refer immediately': 'তীব্র রক্তাল্পতা — এখনই রেফার করুন',
    'Anemia detected — supplement and follow up': 'রক্তাল্পতা সনাক্ত — সাপ্লিমেন্ট দিন ও ফলো-আপ করুন',
    'High blood glucose — diabetes screening indicated': 'উচ্চ রক্তে গ্লুকোজ — ডায়াবেটিস স্ক্রিনিং প্রয়োজন',
    'Referral recommended — treat-at-community overridden': 'রেফারেল সুপারিশ করা হয়েছে — কমিউনিটি চিকিৎসা বাতিল করা হয়েছে',
    'Diabetes risk moderate (FINDRISC 12–14) — add NCD assessment': 'ডায়াবেটিস ঝুঁকি মাঝারি (FINDRISC ১২–১৪) — NCD মূল্যায়ন যুক্ত করুন',
    'Diabetes risk high (FINDRISC 15–20) — add NCD assessment': 'ডায়াবেটিস ঝুঁকি বেশি (FINDRISC ১৫–২০) — NCD মূল্যায়ন যুক্ত করুন',
    'Diabetes risk very high (FINDRISC ≥ 21) — add NCD assessment': 'ডায়াবেটিস ঝুঁকি অত্যন্ত বেশি (FINDRISC ≥ ২১) — NCD মূল্যায়ন যুক্ত করুন',
    'CVD risk ≥ 10% (Framingham) — NCD management indicated': 'CVD ঝুঁকি ≥ ১০% (Framingham) — NCD ব্যবস্থাপনা প্রয়োজন',
    'CVD risk ≥ 20% (Framingham) — high cardiovascular risk': 'CVD ঝুঁকি ≥ ২০% (Framingham) — উচ্চ হৃদরোগের ঝুঁকি',
    'BP trend alert (CUSUM) — rising blood pressure pattern detected': 'রক্তচাপ ট্রেন্ড সতর্কতা (CUSUM) — বাড়তে থাকা রক্তচাপের ধরন সনাক্ত',
    'BP trend alert (EWMA) — blood pressure control worsening': 'রক্তচাপ ট্রেন্ড সতর্কতা (EWMA) — রক্তচাপ নিয়ন্ত্রণ খারাপ হচ্ছে',
    'BP trend alert — increasing > 4 mmHg per visit': 'রক্তচাপ ট্রেন্ড সতর্কতা — প্রতি ভিজিটে > ৪ mmHg বৃদ্ধি',
    'High risk of adverse outcome (miniPIERS ≥ 25%) — close monitoring needed': 'প্রতিকূল ফলাফলের উচ্চ ঝুঁকি (miniPIERS ≥ ২৫%) — ঘনিষ্ঠ পর্যবেক্ষণ প্রয়োজন',
    'Critical risk of adverse outcome (miniPIERS ≥ 50%) — refer immediately': 'প্রতিকূল ফলাফলের সংকটজনক ঝুঁকি (miniPIERS ≥ ৫০%) — এখনই রেফার করুন',
    'NCD service provided — enrol patient in NCD programme': 'NCD সেবা প্রদান করা হয়েছে — রোগীকে NCD প্রোগ্রামে নিবন্ধন করুন',
    'Patient requires eye care referral — document referral facility': 'রোগীর চক্ষু সেবার রেফারেল প্রয়োজন — রেফারেল প্রতিষ্ঠান লিখুন',
    'WHO HEARTS: systolic ≥ 160 or diastolic ≥ 100 = severe hypertension': 'WHO HEARTS: সিস্টোলিক ≥ ১৬০ বা ডায়াস্টোলিক ≥ ১০০ = তীব্র উচ্চ রক্তচাপ',
    'WHO HEARTS: systolic ≥ 140 or diastolic ≥ 90 = stage 1 hypertension': 'WHO HEARTS: সিস্টোলিক ≥ ১৪০ বা ডায়াস্টোলিক ≥ ৯০ = স্টেজ ১ উচ্চ রক্তচাপ',
    'WHO IMCI: general danger sign = refer urgently': 'WHO IMCI: সাধারণ বিপদ চিহ্ন = জরুরি রেফার করুন',
    'WHO IMCI: chest indrawing = severe pneumonia': 'WHO IMCI: বুক ভেতরে টানা = তীব্র নিউমোনিয়া',
    'WHO IMCI: fast breathing without chest indrawing = pneumonia': 'WHO IMCI: বুক না টেনে দ্রুত শ্বাস = নিউমোনিয়া',
    'WHO: MUAC < 11.5 cm = severe acute malnutrition': 'WHO: MUAC < ১১.৫ সেমি = তীব্র অপুষ্টি',
    'WHO: MUAC 11.5–12.5 cm = moderate acute malnutrition': 'WHO: MUAC ১১.৫–১২.৫ সেমি = মাঝারি অপুষ্টি',
    'WHO ANC: Hb < 7 g/dL = severe anemia requiring referral': 'WHO ANC: Hb < ৭ g/dL = তীব্র রক্তাল্পতা, রেফারেল প্রয়োজন',
    'WHO ANC: Hb < 11 g/dL = anemia in pregnancy': 'WHO ANC: Hb < ১১ g/dL = গর্ভাবস্থায় রক্তাল্পতা',
    'WHO PEN: glucose > 200 mg/dL random or > 126 mg/dL fasting = diabetes threshold': 'WHO PEN: র\u200d্যান্ডম গ্লুকোজ > ২০০ mg/dL বা খালি পেটে > ১২৬ mg/dL = ডায়াবেটিসের সীমা',
    'WHO: cough ≥ 2 weeks is a TB indicator — screen urgently': 'WHO: কাশি ≥ ২ সপ্তাহ যক্ষ্মার লক্ষণ — জরুরি স্ক্রিনিং করুন',
    'FINDRISC score 12–14: moderate diabetes risk (1 in 6 chance over 10 years)': 'FINDRISC স্কোর ১২–১৪: মাঝারি ডায়াবেটিস ঝুঁকি (১০ বছরে ৬-এ ১ সম্ভাবনা)',
    'FINDRISC score 15–20: high diabetes risk (1 in 3 chance over 10 years)': 'FINDRISC স্কোর ১৫–২০: উচ্চ ডায়াবেটিস ঝুঁকি (১০ বছরে ৩-এ ১ সম্ভাবনা)',
    'FINDRISC score ≥ 21: very high diabetes risk (1 in 2 chance over 10 years)': 'FINDRISC স্কোর ≥ ২১: অত্যন্ত উচ্চ ডায়াবেটিস ঝুঁকি (১০ বছরে ২-এ ১ সম্ভাবনা)',
    'Framingham No-Lab: 10-year CVD risk ≥ 10% — NCD management indicated': 'Framingham No-Lab: ১০-বছরের CVD ঝুঁকি ≥ ১০% — NCD ব্যবস্থাপনা প্রয়োজন',
    'Framingham No-Lab: 10-year CVD risk ≥ 20% — high cardiovascular risk': 'Framingham No-Lab: ১০-বছরের CVD ঝুঁকি ≥ ২০% — উচ্চ হৃদরোগের ঝুঁকি',
    'CUSUM: cumulative BP rise exceeds decision threshold (h = 40 mmHg)': 'CUSUM: সঞ্চিত রক্তচাপ বৃদ্ধি সিদ্ধান্তের সীমা অতিক্রম করেছে (h = ৪০ mmHg)',
    'EWMA: smoothed BP trend has crossed the upper control limit': 'EWMA: সমন্বিত রক্তচাপ ট্রেন্ড উপরের নিয়ন্ত্রণ সীমা অতিক্রম করেছে',
    'Linear slope: BP increasing at > 4 mmHg per visit': 'লিনিয়ার স্লোপ: প্রতি ভিজিটে রক্তচাপ > ৪ mmHg বাড়ছে',
    'miniPIERS: predicted adverse maternal outcome risk ≥ 25%': 'miniPIERS: প্রত্যাশিত প্রতিকূল মাতৃত্ব ফলাফলের ঝুঁকি ≥ ২৫%',
    'miniPIERS: predicted adverse maternal outcome risk ≥ 50% — refer now': 'miniPIERS: প্রত্যাশিত প্রতিকূল মাতৃত্ব ফলাফলের ঝুঁকি ≥ ৫০% — এখনই রেফার করুন',
    'NCD service provided during cataract visit — NCD enrolment recommended': 'ছানি ভিজিটের সময় NCD সেবা প্রদান — NCD নিবন্ধন সুপারিশ করা হয়েছে',
    'Eye test outcome requires specialist referral': 'চোখ পরীক্ষার ফলাফলে বিশেষজ্ঞের রেফারেল প্রয়োজন',
    'Based on symptoms and patient history': 'লক্ষণ ও রোগীর ইতিহাসের ভিত্তিতে',
    'Start Assessment': 'মূল্যায়ন শুরু করুন',
    'Add section manually': 'নিজে বিভাগ যুক্ত করুন',
    'Skip this assessment?': 'এই মূল্যায়ন এড়িয়ে যাবেন?',
    '{p0} was recommended because: {p1}.  Skipping will create a follow-up task so it surfaces next visit.': '{p0} সুপারিশ করা হয়েছিল কারণ: {p1}। এড়িয়ে গেলে একটি ফলো-আপ কাজ তৈরি হবে যা পরের ভিজিটে দেখা যাবে।',
    'Keep': 'রাখুন',
    'Skip anyway': 'তবুও এড়িয়ে যান',
    'ICCM / Child Illness': 'ICCM / শিশু অসুস্থতা',
    'Pregnant Woman Registration': 'গর্ভবতী মা নিবন্ধন',
    'PNC': 'PNC',
    'Neonate Assessment': 'নবজাতক মূল্যায়ন',
    'Assessment': 'মূল্যায়ন',
    'Neonate assessment (age < 2 months)': 'নবজাতক মূল্যায়ন (বয়স < ২ মাস)',
    'Child illness assessment (WHO IMCI)': 'শিশু অসুস্থতা মূল্যায়ন (WHO IMCI)',
    'Antenatal care — pregnancy confirmed': 'প্রসবপূর্ব সেবা — গর্ভধারণ নিশ্চিত',
    'Postnatal care — within 6 weeks of delivery': 'প্রসবোত্তর সেবা — প্রসবের ৬ সপ্তাহের মধ্যে',
    'TB screening — WHO 4-symptom screen': 'যক্ষ্মা স্ক্রিনিং — WHO ৪-লক্ষণ স্ক্রিন',
    'NCD — hypertension review': 'NCD — উচ্চ রক্তচাপ পর্যালোচনা',
    'NCD — diabetes symptoms': 'NCD — ডায়াবেটিসের লক্ষণ',
    'Nutrition assessment — malnutrition indicators': 'পুষ্টি মূল্যায়ন — অপুষ্টির লক্ষণ',
    'Immunization — vaccines overdue': 'টিকাদান — বাকি থাকা টিকা',
    'Manually added': 'নিজে যুক্ত করা হয়েছে',
    'Family planning — unmet need or counselling due': 'পরিবার পরিকল্পনা — অপূর্ণ চাহিদা বা কাউন্সেলিং বাকি',
    'Cataract / eye disease — visual symptoms or known diagnosis': 'ছানি / চোখের রোগ — দৃষ্টি সংক্রান্ত লক্ষণ বা পরিচিত রোগ নির্ণয়',
    'Eye care — visual symptoms requiring eye test': 'চক্ষু সেবা — চোখ পরীক্ষার প্রয়োজন এমন লক্ষণ',
    'Step 1 · Symptoms': 'ধাপ ১ · লক্ষণ',
    'Step 2 · Triage': 'ধাপ ২ · ট্রায়াজ',
    'Step 3 · Assessment': 'ধাপ ৩ · মূল্যায়ন',
    'AI noticed something serious': 'এআই একটি গুরুত্বপূর্ণ বিষয় লক্ষ্য করেছে',
    'AI flagged a concern': 'এআই একটি সমস্যা চিহ্নিত করেছে',
    'AI identified a programme': 'এআই একটি প্রোগ্রাম চিহ্নিত করেছে',
    'AI asks you to check these now': 'এআই এখন এগুলো যাচাই করতে বলছে',
    'Take temperature': 'তাপমাত্রা নিন',
    'Place thermometer under arm for 1 minute': 'থার্মোমিটার বগলে ১ মিনিট রাখুন',
    'Count breaths in 1 minute': '১ মিনিটে শ্বাস গুনুন',
    'Watch the chest go up and down — count for 60 seconds': 'বুক ওঠানামা লক্ষ্য করুন — ৬০ সেকেন্ড গুনুন',
    'Look at the chest': 'বুক দেখুন',
    'Does the chest go IN when breathing? (chest in-drawing)': 'শ্বাস নেওয়ার সময় বুক ভেতরে যায়? (বুক ভেতরে টানা)',
    'Take blood pressure': 'রক্তচাপ নিন',
    'Left arm, patient seated, at rest for 5 minutes': 'বাম হাত, রোগী বসা, ৫ মিনিট বিশ্রামে',
    'Weigh the patient': 'রোগীর ওজন নিন',
    'Remove shoes — record to nearest 0.1 kg': 'জুতা খুলুন — নিকটতম ০.১ কেজিতে রেকর্ড করুন',
    'Measure fundal height': 'ফান্ডাল উচ্চতা মাপুন',
    'Pubic symphysis to uterine fundus in cm': 'পিউবিক সিম্ফাইসিস থেকে জরায়ু ফান্ডাস পর্যন্ত সেমিতে',
    'AI identified: ': 'এআই চিহ্নিত করেছে: ',
    ' programme': ' প্রোগ্রাম',
    'Opening checklist →': 'খোলার চেকলিস্ট →',
    'Open checklist →': 'চেকলিস্ট খুলুন →',
    'Start routine visit →': 'নিয়মিত ভিজিট শুরু করুন →',
    '🎙 AI Scribe — tap to fill the form by voice': '🎙 এআই স্ক্রাইব — ভয়েস দিয়ে ফর্ম পূরণ করতে চাপুন',
    'SK talks to her/him — fields fill automatically': 'এসকে তার সাথে কথা বলেন — ঘর স্বয়ংক্রিয়ভাবে পূরণ হয়',
    'Voice capture complete': 'ভয়েস ক্যাপচার সম্পন্ন',
    'Listening… tap to stop': 'শোনা হচ্ছে… থামাতে চাপুন',
    'AI is reviewing the recording': 'এআই রেকর্ডিং পর্যালোচনা করছে',
    'Analysing symptoms…': 'লক্ষণ বিশ্লেষণ করা হচ্ছে…',
    'Transcribing your recording…': 'আপনার রেকর্ডিং লেখায় রূপান্তর হচ্ছে…',
    'Tap to record again': 'আবার রেকর্ড করতে চাপুন',
    'Tap anywhere to stop': 'থামাতে যেকোনো জায়গায় চাপুন',
    'Voice review failed': 'ভয়েস পর্যালোচনা ব্যর্থ',
    'Tap to try again': 'আবার চেষ্টা করতে চাপুন',
    'No symptoms detected': 'কোনো লক্ষণ সনাক্ত হয়নি',
    "Speak the patient's symptoms clearly, then tap to try again": 'রোগীর লক্ষণ স্পষ্টভাবে বলুন, তারপর আবার চেষ্টা করতে চাপুন',
    'Before You Knock': 'দরজায় যাওয়ার আগে',
    'Pregnant · ANC': 'গর্ভবতী · ANC',
    'Known HTN': 'পরিচিত উচ্চ রক্তচাপ',
    'Known DM': 'পরিচিত ডায়াবেটিস',
    'TB screen due': 'যক্ষ্মা স্ক্রিন বাকি',
    'Under 5 · IMCI': '৫ বছরের নিচে · IMCI',
    'Routine visit': 'নিয়মিত ভিজিট',
    'SK ASKS THE FAMILY 👋': 'এসকে পরিবারকে জিজ্ঞাসা করেন 👋',
    'How many days unwell?': 'কতদিন ধরে অসুস্থ?',
    '1 day': '১ দিন',
    '2–3 days': '২–৩ দিন',
    '4+ days': '৪+ দিন',
    '1': '১',
    '2-3': '২-৩',
    '4+': '৪+',
    'Start Checkup →': 'পরীক্ষা শুরু করুন →',
    'No symptoms selected — please check symptoms before proceeding.': 'কোনো লক্ষণ নির্বাচিত নয় — এগিয়ে যাওয়ার আগে লক্ষণ চেক করুন।',
    'Continue anyway': 'তবুও চালিয়ে যান',
    'Other symptoms / Notes': 'অন্যান্য লক্ষণ / নোট',
    'Type symptom manually…': 'লক্ষণ নিজে লিখুন…',
    'Add from list': 'তালিকা থেকে যুক্ত করুন',
    'AI-Detected Symptoms': 'এআই-সনাক্ত লক্ষণ',
    'Review each symptom. Tap × to remove anything incorrect, or add what is missing.': 'প্রতিটি লক্ষণ পর্যালোচনা করুন। ভুল হলে × চেপে বাদ দিন, অথবা যা বাকি তা যুক্ত করুন।',
    'Search or type symptom…': 'লক্ষণ খুঁজুন বা লিখুন…',
    'Search symptoms…': 'লক্ষণ খুঁজুন…',
    'Type 3+ letters to find more symptoms': 'আরও লক্ষণ খুঁজতে ৩+ অক্ষর লিখুন',
    'No symptoms found': 'কোনো লক্ষণ পাওয়া যায়নি',
    'General': 'সাধারণ',
    'Added from search': 'খোঁজ থেকে যুক্ত হয়েছে',
    'Search to add more symptoms': 'আরও লক্ষণ যুক্ত করতে খুঁজুন',
    'Search for symptoms': 'লক্ষণ খুঁজুন',
    'New program assessment': 'নতুন প্রোগ্রাম মূল্যায়ন',
    'Add to this visit': 'এই ভিজিটে যুক্ত করুন',
    'Skip for now': 'এখন এড়িয়ে যান',
    'symptom selected': 'লক্ষণ নির্বাচিত',
    'Or type a symptom manually…': 'অথবা নিজে একটি লক্ষণ লিখুন…',
    '+ Add': '+ যুক্ত করুন',
    'Show symptom list': 'লক্ষণ তালিকা দেখান',
    'Hide symptom list': 'লক্ষণ তালিকা লুকান',
    'Add symptoms': 'লক্ষণ যুক্ত করুন',
    'Tap to add or remove. AI-detected symptoms are already ticked — press Done when finished.': 'যুক্ত বা বাদ দিতে চাপুন। এআই-সনাক্ত লক্ষণ আগেই টিক দেওয়া — শেষ হলে সম্পন্ন চাপুন।',
    'All symptoms already added.': 'সব লক্ষণ ইতিমধ্যে যুক্ত করা হয়েছে।',
    'Remove symptom': 'লক্ষণ বাদ দিন',
    'Programmes': 'প্রোগ্রাম',
    'AI recommended programmes': 'এআই সুপারিশকৃত প্রোগ্রাম',
    'AI is reviewing the symptoms…': 'এআই লক্ষণ পর্যালোচনা করছে…',
    'Checking BRAC protocols and Bangladesh national clinical guidelines': 'BRAC প্রোটোকল ও বাংলাদেশ জাতীয় ক্লিনিকাল গাইডলাইন যাচাই করা হচ্ছে',
    'Unable to load AI recommendations': 'এআই সুপারিশ লোড করা যায়নি',
    'Continue with the current enrolment or add a programme manually.': 'বর্তমান নিবন্ধন নিয়ে চালিয়ে যান বা নিজে একটি প্রোগ্রাম যুক্ত করুন।',
    'Current Programme': 'বর্তমান প্রোগ্রাম',
    'Patient is not enrolled in any programme yet.': 'রোগী এখনও কোনো প্রোগ্রামে নিবন্ধিত নয়।',
    'Selected symptoms are consistent with this programme.': 'নির্বাচিত লক্ষণ এই প্রোগ্রামের সাথে সামঞ্জস্যপূর্ণ।',
    'Selected symptoms do not strongly match this programme.': 'নির্বাচিত লক্ষণ এই প্রোগ্রামের সাথে ভালোভাবে মেলে না।',
    'AI Recommended Programmes': 'এআই সুপারিশকৃত প্রোগ্রাম',
    'Current': 'বর্তমান',
    'Add': 'যুক্ত করুন',
    'Added': 'যুক্ত হয়েছে',
    'This will open the screening questions for the selected programme. You can remove it later from the recommendations list.': 'এটি নির্বাচিত প্রোগ্রামের স্ক্রিনিং প্রশ্ন খুলবে। পরে সুপারিশ তালিকা থেকে এটি বাদ দিতে পারবেন।',
    'Yes, add': 'হ্যাঁ, যুক্ত করুন',
    "The AI recommended this programme based on the patient's symptoms and history. Are you sure you want to skip it?": 'রোগীর লক্ষণ ও ইতিহাসের ভিত্তিতে এআই এই প্রোগ্রাম সুপারিশ করেছে। আপনি কি নিশ্চিত এটি এড়িয়ে যেতে চান?',
    'Yes, skip': 'হ্যাঁ, এড়িয়ে যান',
    'Keep it': 'রেখে দিন',
    'Confirm the assessments below. You can add or remove before continuing.': 'নিচের মূল্যায়নগুলো নিশ্চিত করুন। চালিয়ে যাওয়ার আগে যুক্ত বা বাদ দিতে পারেন।',
    'No programmes selected. Add one before continuing, or proceed with a routine visit.': 'কোনো প্রোগ্রাম নির্বাচিত নয়। চালিয়ে যাওয়ার আগে একটি যুক্ত করুন, বা নিয়মিত ভিজিট দিয়ে এগিয়ে যান।',
    'Add another programme': 'আরেকটি প্রোগ্রাম যুক্ত করুন',
    'Back': 'পেছনে',
    'Cross-programme alert': 'আন্তঃ-প্রোগ্রাম সতর্কতা',
    'Add a programme': 'একটি প্রোগ্রাম যুক্ত করুন',
    'Tap to select. Already-recommended programmes are hidden.': 'নির্বাচন করতে চাপুন। যেগুলো আগেই সুপারিশ করা হয়েছে তা দেখানো হচ্ছে না।',
    'All programmes already selected.': 'সব প্রোগ্রাম ইতিমধ্যে নির্বাচিত।',
    'Continue (no programme)': 'চালিয়ে যান (কোনো প্রোগ্রাম নেই)',
    'BRAC': 'BRAC',
    'BD national': 'বাংলাদেশ জাতীয়',
    'Context': 'প্রসঙ্গ',
    'Symptom': 'লক্ষণ',
    'Visit Complete': 'ভিজিট সম্পন্ন',
    'Assessment saved': 'মূল্যায়ন সংরক্ষিত হয়েছে',
    'Referral recommended based on clinical findings': 'ক্লিনিকাল ফলাফলের ভিত্তিতে রেফারেল সুপারিশ করা হয়েছে',
    'Book Teleconsult': 'টেলি-পরামর্শ বুক করুন',
    'Send Counselling Message': 'কাউন্সেলিং বার্তা পাঠান',
    'Create Referral': 'রেফারেল তৈরি করুন',
    'Back to Home': 'হোমে ফিরুন',
    'Done for Now': 'এখন শেষ',
    '📱 Call a doctor now': '📱 এখনই ডাক্তারকে ফোন করুন',
    '🏥 Book hospital visit & refer': '🏥 হাসপাতাল ভিজিট বুক করুন ও রেফার করুন',
    'Members in this household': 'এই পরিবারের সদস্য',
    'First ANC Visit — Key Messages': 'প্রথম ANC ভিজিট — মূল বার্তা',
    'Congratulations on this pregnancy! Today we: • Registered you in the ANC programme • Measured your blood pressure and weight • Scheduled your next visit in 4 weeks  Remember to: • Take your iron-folate tablet every day • Eat nutritious food — dal, eggs, leafy vegetables • Rest and avoid heavy lifting • Come immediately if you have heavy bleeding, severe headache, or blurred vision': 'আপনার গর্ভধারণে অভিনন্দন! আজ আমরা: • আপনাকে ANC প্রোগ্রামে নিবন্ধিত করেছি • আপনার রক্তচাপ ও ওজন মেপেছি • ৪ সপ্তাহ পরে আপনার পরের ভিজিট নির্ধারণ করেছি\n\nমনে রাখবেন: • প্রতিদিন আয়রন-ফলিক ট্যাবলেট খান • পুষ্টিকর খাবার খান — ডাল, ডিম, শাক-সবজি • বিশ্রাম নিন এবং ভারী কাজ এড়িয়ে চলুন • অতিরিক্ত রক্তক্ষরণ, তীব্র মাথাব্যথা বা ঝাপসা দৃষ্টি হলে এখনই আসুন',
    'Vitals & form': 'ভাইটালস ও ফর্ম',
    'AI recommends': 'এআই সুপারিশ করে',
    'How are you?': 'আপনি কেমন আছেন?',
    'Assessment forms': 'মূল্যায়ন ফর্ম',
    'form': 'ফর্ম',
    'Summary': 'সারাংশ',
    "ALSO COVER WHILE YOU'RE HERE": 'এখানে থাকতে এগুলোও কভার করুন',
    'AI checked all findings': 'এআই সব ফলাফল যাচাই করেছে',
    'Step %1 of 3': 'ধাপ %1 এর ৩',
    'Back to visits': 'ভিজিটে ফিরুন',
    'Leave this visit?': 'এই ভিজিট থেকে বের হবেন?',
    'The symptoms, programmes and form entries on this visit will be discarded. You will start fresh next time.': 'এই ভিজিটের লক্ষণ, প্রোগ্রাম ও ফর্মের তথ্য বাতিল হয়ে যাবে। পরের বার নতুন করে শুরু করবেন।',
    'Stay on this visit': 'এই ভিজিটে থাকুন',
    'Yes, leave': 'হ্যাঁ, বের হন',
    'Generating care plan…': 'কেয়ার প্ল্যান তৈরি হচ্ছে…',
    'AI is reviewing the assessment. This takes a few seconds.': 'এআই মূল্যায়ন পর্যালোচনা করছে। এটি কয়েক সেকেন্ড সময় নেয়।',
    'Could not generate care plan': 'কেয়ার প্ল্যান তৈরি করা যায়নি',
    'The assessment has been saved. Tap Retry to try again, or continue without AI recommendations.': 'মূল্যায়ন সংরক্ষিত হয়েছে। আবার চেষ্টা করতে Retry চাপুন, বা এআই সুপারিশ ছাড়া চালিয়ে যান।',
    'Skip — go to home': 'এড়িয়ে যান — হোমে যান',
    'Danger signs to watch for': 'যে বিপদ চিহ্নগুলো খেয়াল রাখতে হবে',
    'Clinical findings': 'ক্লিনিকাল ফলাফল',
    'Next actions': 'পরবর্তী কাজ',
    'Counselling points': 'কাউন্সেলিং পয়েন্ট',
    'Medication advice': 'ওষুধের পরামর্শ',
    'Follow-up schedule': 'ফলো-আপ সময়সূচি',
    'Referral recommendation': 'রেফারেল সুপারিশ',
    'WhatsApp counselling (Bangla)': 'WhatsApp কাউন্সেলিং (বাংলা)',
    'AI rationale': 'এআই যুক্তি',
    'Human review recommended': 'মানুষ দ্বারা পর্যালোচনার সুপারিশ',
    'High confidence': 'উচ্চ আত্মবিশ্বাস',
    'Referral required': 'রেফারেল প্রয়োজন',
    'No referral needed': 'রেফারেলের প্রয়োজন নেই',
    'NOW': 'এখনই',
    'TODAY': 'আজ',
    'THIS WEEK': 'এই সপ্তাহে',
    'ROUTINE': 'নিয়মিত',
    'High': 'বেশি',
    'Medium': 'মাঝারি',
    'Low': 'কম',
    'Copy': 'কপি করুন',
    'Copied!': 'কপি হয়েছে!',
    'Send via SMS': 'SMS-এ পাঠান',
    'Send via WhatsApp': 'WhatsApp-এ পাঠান',
    'Send this message': 'এই বার্তা পাঠান',
    'AI Counselling Guide': 'এআই কাউন্সেলিং গাইড',
    'WhatsApp is not installed on this device.': 'এই ডিভাইসে WhatsApp ইনস্টল করা নেই।',
    'SMS is not available on this device.': 'এই ডিভাইসে SMS সুবিধা নেই।',
    'Save & Go Home': 'সংরক্ষণ করে হোমে যান',
    'This is an AI proposal. Review and accept to proceed.': 'এটি একটি এআই প্রস্তাব। পর্যালোচনা করে গ্রহণ করুন।',
    'Available when online': 'অনলাইন থাকলে উপলব্ধ',
    'AI service was unavailable. Care plan is based on clinical guidelines. Review and adjust based on your assessment.': 'এআই সেবা উপলব্ধ ছিল না। কেয়ার প্ল্যান ক্লিনিকাল গাইডলাইনের ভিত্তিতে তৈরি। আপনার মূল্যায়নের ভিত্তিতে পর্যালোচনা ও সমন্বয় করুন।',
    'Teleconsult': 'টেলি-পরামর্শ',
    'Coming soon': 'শীঘ্রই আসছে',
    'Video consultation with a doctor will be available here. The SK can initiate a call directly from a completed visit.': 'এখানে ডাক্তারের সাথে ভিডিও পরামর্শ পাওয়া যাবে। এসকে সম্পন্ন ভিজিট থেকে সরাসরি কল শুরু করতে পারবেন।',
    'Start Video Call': 'ভিডিও কল শুরু করুন',
    'Send SMS to Doctor': 'ডাক্তারকে SMS পাঠান',
    'Counselling Messages': 'কাউন্সেলিং বার্তা',
    'AI-generated health counselling': 'এআই-তৈরি স্বাস্থ্য কাউন্সেলিং',
    'Copy message': 'বার্তা কপি করুন',
    'No counselling message generated for this visit.': 'এই ভিজিটের জন্য কোনো কাউন্সেলিং বার্তা তৈরি হয়নি।',
    'Training Hub': 'প্রশিক্ষণ হাব',
    'Short videos · Learn at your own pace': 'ছোট ভিডিও · নিজের গতিতে শিখুন',
    'Certificates': 'সার্টিফিকেট',
    'Complete modules to earn programme certificates': 'প্রোগ্রাম সার্টিফিকেট পেতে মডিউল সম্পন্ন করুন',
    '🏆 Top SKs this month': '🏆 এই মাসের শীর্ষ এসকে',
    '(You)': '(আপনি)',
    '⚡ ': '⚡ ',
    ' pts away from 1st place · Watch 3 more videos to catch up!': ' পয়েন্ট দূরে ১ম স্থান থেকে · এগিয়ে যেতে আরও ৩টি ভিডিও দেখুন!',
    "TODAY'S LESSONS — BASED ON YOUR VISITS": 'আজকের পাঠ — আপনার ভিজিট অনুযায়ী',
    'Your progress this month': 'এই মাসে আপনার অগ্রগতি',
    'NOW PLAYING': 'চলছে',
    '✓ COMPLETED': '✓ সম্পন্ন',
    '🔒 LOCKED': '🔒 লক করা',
    'New': 'নতুন',
    'Locked': 'লক করা',
    'Videos watched': 'দেখা ভিডিও',
    'Points earned': 'পয়েন্ট অর্জিত',
    'Day streak 🔥': 'দিনের ধারা 🔥',
    'Complete earlier lessons to unlock this one': 'এটি আনলক করতে আগের পাঠ সম্পন্ন করুন',
    'Personalised Coaching': 'ব্যক্তিগতকৃত কোচিং',
    'Last synced': 'সর্বশেষ সিঙ্ক',
    'Coaching': 'কোচিং',
    'Leaderboard': 'লিডারবোর্ড',
    'MICRO-COACHING': 'মাইক্রো-কোচিং',
    'Tap to answer': 'উত্তর দিতে চাপুন',
    'Refreshers': 'রিফ্রেশার',
    'No refreshers yet.': 'এখনও কোনো রিফ্রেশার নেই।',
    'Training': 'প্রশিক্ষণ',
    'See all': 'সব দেখুন',
    'All Modules': 'সব মডিউল',
    'All Time': 'সব সময়',
    'This Month': 'এই মাস',
    'This Week': 'এই সপ্তাহ',
    'Dhamrai Upazila · 28 SKs': 'ধামরাই উপজেলা · ২৮ জন এসকে',
    'Updated': 'আপডেট হয়েছে',
    'XP': 'XP',
    'd': 'দিন',
    'You': 'আপনি',
    "TODAY'S FOCUS": 'আজকের ফোকাস',
    'ALL MODULES': 'সব মডিউল',
    'min': 'মিনিট',
    'Passed': 'উত্তীর্ণ',
    'Start': 'শুরু করুন',
    'Review': 'পর্যালোচনা',
    'of': 'এর',
    'Take Quiz': 'কুইজ দিন',
    'Quick Quiz': 'সংক্ষিপ্ত কুইজ',
    'Question': 'প্রশ্ন',
    'Check Answer': 'উত্তর যাচাই করুন',
    'Quiz Complete': 'কুইজ সম্পন্ন',
    'You passed!': 'আপনি উত্তীর্ণ হয়েছেন!',
    'Not quite — review the module and try again.': 'একদম ঠিক না — মডিউল পর্যালোচনা করে আবার চেষ্টা করুন।',
    'Try Again': 'আবার চেষ্টা করুন',
    'Back to Training': 'প্রশিক্ষণে ফিরুন',
    'Quiz not available yet': 'কুইজ এখনও উপলব্ধ নয়',
    'Questions for this module are being prepared. Complete the lesson cards and check back later.': 'এই মডিউলের প্রশ্ন তৈরি হচ্ছে। পাঠ কার্ড সম্পন্ন করে পরে দেখুন।',
    'Why?': 'কেন?',
    'cards': 'কার্ড',
    'questions': 'প্রশ্ন',
    'Start Course': 'কোর্স শুরু করুন',
    'CURRICULUM': 'কারিকুলাম',
    'Micro-coaching': 'মাইক্রো-কোচিং',
    'Learning Card': 'লার্নিং কার্ড',
    'Quiz': 'কুইজ',
    "TODAY'S FOCUS — BASED ON YOUR GAPS": 'আজকের ফোকাস — আপনার ঘাটতি অনুযায়ী',
    'Learning {i} of {n}': 'লার্নিং {n}-এর {i}',
    'Learning {p0} of {p1}': 'লার্নিং {p1}-এর {p0}',
    'ALL TRAINING MODULES': 'সব প্রশিক্ষণ মডিউল',
    'Hypertension screening': 'উচ্চ রক্তচাপ স্ক্রিনিং',
    'Yes / No — strengthens AI clinical decision support.': 'হ্যাঁ / না — এআই ক্লিনিকাল সিদ্ধান্ত সহায়তাকে শক্তিশালী করে।',
    'Sudden numbness or weakness on one side — immediate emergency referral.': 'একপাশে আকস্মিক অবশভাব বা দুর্বলতা — এখনই জরুরি রেফারেল।',
    'Could not save the assessment. It is kept on this device — please try again.': 'মূল্যায়ন সংরক্ষণ করা যায়নি। এটি ডিভাইসে রাখা আছে — আবার চেষ্টা করুন।',
    'Form configuration could not be loaded. Please restart the app.': 'ফর্ম কনফিগারেশন লোড করা যায়নি। অ্যাপ পুনরায় চালু করুন।',
    'No assessment pathways activated.': 'কোনো মূল্যায়ন পথ চালু করা হয়নি।',
    '/min': '/মিনিট',
    '+ Add Reading': '+ পাঠ যুক্ত করুন',
    'Reading': 'পাঠ',
    'Remove reading': 'পাঠ বাদ দিন',
    '(auto)': '(স্বয়ংক্রিয়)',
    'Please complete required fields': 'আবশ্যক ঘরগুলো পূরণ করুন',
    'Symptoms from Step 1': 'ধাপ ১ থেকে লক্ষণ',
    'No symptoms selected in Step 1.': 'ধাপ ১-এ কোনো লক্ষণ নির্বাচিত নয়।',
    'Enrolled Programmes': 'নিবন্ধিত প্রোগ্রাম',
    'Recommended Programmes': 'সুপারিশকৃত প্রোগ্রাম',
    'Today': 'আজ',
    'Systolic': 'সিস্টোলিক',
    'Diastolic': 'ডায়াস্টোলিক',
    'Weight gain': 'ওজন বৃদ্ধি',
    'Urine protein': 'প্রস্রাবে প্রোটিন',
    'Neg': 'নেগেটিভ',
    'Trace': 'সামান্য',
    'Present': 'আছে',
    'Each reading is below its alert line — but they are climbing together across visits. No single rule fires.': 'প্রতিটি পাঠ সতর্কতা সীমার নিচে — কিন্তু ভিজিট জুড়ে একসাথে বাড়ছে। একক কোনো নিয়ম সক্রিয় হয় না।',
    'Readings are stable across visits. No rising trend detected.': 'ভিজিট জুড়ে পাঠ স্থির। কোনো বাড়তি ধারা সনাক্ত হয়নি।',
    'Underweight': 'কম ওজন',
    'Overweight': 'অতিরিক্ত ওজন',
    'Obese': 'স্থূল',
    'Slightly Elevated': 'একটু বেড়ে গেছে',
    'Severe': 'তীব্র',
    'Mild Anaemia': 'মৃদু রক্তাল্পতা',
    'Moderate Anaemia': 'মাঝারি রক্তাল্পতা',
    'Severe Anaemia': 'তীব্র রক্তাল্পতা',
    'Anaemia': 'রক্তাল্পতা',
    'Below 11 g/dL — Anaemia. Counsel on iron-rich diet and IFA adherence.': '১১ g/dL-এর নিচে — রক্তাল্পতা। আয়রন সমৃদ্ধ খাবার ও IFA সেবনের পরামর্শ দিন।',
    'Absent': 'নেই',
    'Expected': 'প্রত্যাশিত',
    'Elevated — advise dietary modification and refer for GDM screening.': 'বেড়ে গেছে — খাদ্যাভ্যাস পরিবর্তনের পরামর্শ দিন ও GDM স্ক্রিনিংয়ের জন্য রেফার করুন।',
    'High blood sugar — refer urgently for diabetes evaluation.': 'উচ্চ রক্তে শর্করা — ডায়াবেটিস মূল্যায়নের জন্য জরুরি রেফার করুন।',
    'mmol/L': 'mmol/L',
    'Gallery': 'গ্যালারি',
    'Form Gallery': 'ফর্ম গ্যালারি',
    'fields': 'ঘর',
    'My Performance': 'আমার পারফরম্যান্স',
    'Week': 'সপ্তাহ',
    'Month': 'মাস',
    'visits this period': 'এই সময়ে ভিজিট',
    'Weekly target': 'সাপ্তাহিক লক্ষ্য',
    'Visits today': 'আজকের ভিজিট',
    'so far': 'এখন পর্যন্ত',
    'Households': 'পরিবার',
    'enrolled': 'নিবন্ধিত',
    'Referrals': 'রেফারেল',
    'this week': 'এই সপ্তাহে',
    'Visits': 'ভিজিট',
    'this period': 'এই সময়ে',
    'VISITS BY PROGRAMME': 'প্রোগ্রাম অনুযায়ী ভিজিট',
    'RECENT ACTIVITY': 'সাম্প্রতিক কার্যক্রম',
    'Yesterday': 'গতকাল',
    'Completed': 'সম্পন্ন',
    'Referred': 'রেফার করা হয়েছে',
    'Could not load performance data': 'পারফরম্যান্স তথ্য লোড করা যায়নি',
    'My performance': 'আমার পারফরম্যান্স',
    'Jahnara Begum · SK ID 4521 · Manikganj Sadar': 'জাহানারা বেগম · এসকে আইডি ৪৫২১ · মানিকগঞ্জ সদর',
    'PERFORMANCE SCORE': 'পারফরম্যান্স স্কোর',
    'Blends visit completion, referral follow-through & SLA compliance': 'ভিজিট সম্পন্ন, রেফারেল অনুসরণ ও SLA পালনের সমন্বয়',
    'SLA COMPLIANCE': 'SLA পালন',
    'HIGH-RISK RESPONSE': 'উচ্চ-ঝুঁকি সাড়া',
    'VISIT TREND': 'ভিজিট ধারা',
    '↑ steady': '↑ স্থির',
    'Visits Completed': 'সম্পন্ন ভিজিট',
    'Referrals Made': 'প্রদত্ত রেফারেল',
    'Referrals Completed': 'সম্পন্ন রেফারেল',
    'Households Covered': 'কভারকৃত পরিবার',
    'Avg Visits / Day': 'গড় ভিজিট/দিন',
    'Missed / Overdue': 'বাদ পড়া / বাকি',
    'SERVICE-WISE BREAKDOWN': 'সেবা অনুযায়ী বিভাজন',
    'more visits': 'আরও ভিজিট',
    'Child / Immunisation': 'শিশু / টিকাদান',
    'Household enrolment': 'পরিবার নিবন্ধন',
    "Scan Head's ID": 'প্রধানের আইডি স্ক্যান করুন',
    'Position ID card in the frame': 'আইডি কার্ড ফ্রেমে রাখুন',
    'Or create household manually': 'অথবা নিজে পরিবার তৈরি করুন',
    'Place ID card here': 'আইডি কার্ড এখানে রাখুন',
    'Household Information': 'পরিবারের তথ্য',
    'Step 1 of 2': 'ধাপ ১ এর ২',
    'Household Number': 'পরিবার নম্বর',
    'Auto-generated': 'স্বয়ংক্রিয়ভাবে তৈরি',
    'SS Name': 'SS নাম',
    'Select SS': 'SS নির্বাচন করুন',
    'Village': 'গ্রাম',
    'Select village': 'গ্রাম নির্বাচন করুন',
    'Sub-Village': 'উপ-গ্রাম',
    'Select sub-village': 'উপ-গ্রাম নির্বাচন করুন',
    'Household Type': 'পরিবারের ধরন',
    'Number of Members': 'সদস্য সংখ্যা',
    'Estimated count': 'আনুমানিক সংখ্যা',
    'House Number': 'বাড়ি নম্বর',
    'e.g., 123 A/B': 'যেমন, ১২৩ A/B',
    'Primary Occupation': 'মূল পেশা',
    'Farmer, Labour, Business, etc.': 'কৃষক, শ্রমিক, ব্যবসা, ইত্যাদি',
    'Monthly Income': 'মাসিক আয়',
    'Does any household member have a disability?': 'পরিবারের কোনো সদস্যের প্রতিবন্ধিতা আছে?',
    'Please specify': 'উল্লেখ করুন',
    'Type of disability': 'প্রতিবন্ধিতার ধরন',
    'Household Head Information': 'পরিবার প্রধানের তথ্য',
    'Step 2 of 2': 'ধাপ ২ এর ২',
    'Full Name': 'পূর্ণ নাম',
    "Head's full name": 'প্রধানের পূর্ণ নাম',
    "Father's Name": 'পিতার নাম',
    'As printed on the NID (Bangla)': 'এনআইডিতে মুদ্রিত অনুযায়ী (বাংলা)',
    "Mother's Name": 'মাতার নাম',
    'ID Type': 'আইডির ধরন',
    'ID Number': 'আইডি নম্বর',
    'Birth Registration or NID number': 'জন্ম নিবন্ধন বা এনআইডি নম্বর',
    'Mobile Number': 'মোবাইল নম্বর',
    '+880 1XXX XXXXXX': '+৮৮০ ১XXX XXXXXX',
    'Not Available': 'নেই',
    'DD/MM/YYYY': 'দিন/মাস/বছর',
    'Or Approximate Age': 'অথবা আনুমানিক বয়স',
    'Years': 'বছর',
    'Calculated from DOB': 'জন্ম তারিখ থেকে গণনা করা',
    'Gender': 'লিঙ্গ',
    'Marital Status': 'বৈবাহিক অবস্থা',
    'Disability Status': 'প্রতিবন্ধিতার অবস্থা',
    'Add Household Member': 'পরিবারের সদস্য যুক্ত করুন',
    "Member's full name": 'সদস্যের পূর্ণ নাম',
    'Relationship to Head': 'প্রধানের সাথে সম্পর্ক',
    'Village (if different)': 'গ্রাম (যদি ভিন্ন হয়)',
    'For external members': 'বহিরাগত সদস্যদের জন্য',
    'Scan ID (Optional)': 'আইডি স্ক্যান করুন (ঐচ্ছিক)',
    'Household Enrolled!': 'পরিবার নিবন্ধিত হয়েছে!',
    'Your household has been created successfully.': 'আপনার পরিবার সফলভাবে তৈরি হয়েছে।',
    'Household Details': 'পরিবারের বিবরণ',
    'Members Added': 'যুক্ত হওয়া সদস্য',
    'Add Member': 'সদস্য যুক্ত করুন',
    'Save & Continue': 'সংরক্ষণ করে চালিয়ে যান',
    'This field is required': 'এই ঘরটি আবশ্যক',
    'Please enter a valid email': 'সঠিক ইমেইল লিখুন',
    'Please enter a valid phone number': 'সঠিক ফোন নম্বর লিখুন',
    'Please enter a valid age': 'সঠিক বয়স লিখুন',
    'Please enter a valid date': 'সঠিক তারিখ লিখুন',
    'Enrollment failed': 'নিবন্ধন ব্যর্থ হয়েছে',
    'Household enrolled successfully': 'পরিবার সফলভাবে নিবন্ধিত হয়েছে',
    'Previous': 'পূর্ববর্তী',
    'Save': 'সংরক্ষণ করুন',
    'Submit': 'জমা দিন',
    'Create Household': 'পরিবার তৈরি করুন',
    'Scan Again': 'আবার স্ক্যান করুন',
    'Register a new household in your catchment area': 'আপনার এলাকায় একটি নতুন পরিবার নিবন্ধন করুন',
    '🏠 Household Information': '🏠 পরিবারের তথ্য',
    '👤 Household Head Information': '👤 পরিবার প্রধানের তথ্য',
    '(auto-generated)': '(স্বয়ংক্রিয়ভাবে তৈরি)',
    'Select type': 'ধরন নির্বাচন করুন',
    'Household Head Occupation': 'পরিবার প্রধানের পেশা',
    'Monthly Household Income (BDT)': 'মাসিক পরিবারের আয় (টাকা)',
    'e.g. 12000': 'যেমন ১২০০০',
    'Any person with disability?': 'কোনো ব্যক্তির প্রতিবন্ধিতা আছে?',
    'Number of persons with disability': 'প্রতিবন্ধী ব্যক্তির সংখ্যা',
    'e.g. 1': 'যেমন ১',
    'Total Household Members': 'মোট পরিবারের সদস্য',
    'e.g. 5': 'যেমন ৫',
    'Guardian': 'অভিভাবক',
    'Select guardian from household': 'পরিবার থেকে অভিভাবক নির্বাচন করুন',
    'Continue →': 'চালিয়ে যান →',
    '✓ Create Household': '✓ পরিবার তৈরি করুন',
    'Save Member →': 'সদস্য সংরক্ষণ করুন →',
    'Scan NID card to read number': 'নম্বর পড়তে এনআইডি কার্ড স্ক্যান করুন',
    'NID NUMBER': 'এনআইডি নম্বর',
    'Enter NID number': 'এনআইডি নম্বর লিখুন',
    '✓ Scanned': '✓ স্ক্যান হয়েছে',
    'Clear scan': 'স্ক্যান পরিষ্কার করুন',
    'If member has no NID, enter Birth Registration ID instead.': 'সদস্যের এনআইডি না থাকলে, জন্ম নিবন্ধন নম্বর লিখুন।',
    'Auto-scanning — hold card steady': 'স্বয়ংক্রিয়ভাবে স্ক্যান হচ্ছে — কার্ড স্থির রাখুন',
    'Scanning every ~2 s · tap button to force capture': 'প্রতি ~২ সেকেন্ডে স্ক্যান হচ্ছে · জোর করে ক্যাপচার করতে বাটন চাপুন',
    'Could not read the NID number. Try again or type it in below.': 'এনআইডি নম্বর পড়া যায়নি। আবার চেষ্টা করুন বা নিচে লিখুন।',
    'Camera unavailable. Please type the NID number below.': 'ক্যামেরা উপলব্ধ নেই। নিচে এনআইডি নম্বর লিখুন।',
    "Name, date of birth & NID read from the card — verify, then add father's & mother's names (Bangla) manually.": 'নাম, জন্ম তারিখ ও এনআইডি কার্ড থেকে পড়া হয়েছে — যাচাই করুন, তারপর পিতা ও মাতার নাম (বাংলা) নিজে যুক্ত করুন।',
    '✓ Read from NID · verify the details below': '✓ এনআইডি থেকে পড়া হয়েছে · নিচের তথ্য যাচাই করুন',
    'This person is already in the system — link them to a household instead of registering again.': 'এই ব্যক্তি ইতিমধ্যে সিস্টেমে আছেন — আবার নিবন্ধনের বদলে তাকে একটি পরিবারের সাথে যুক্ত করুন।',
    'If exact DOB is unknown, leave blank and enter approximate age below.': 'সঠিক জন্ম তারিখ না জানা থাকলে, ফাঁকা রেখে নিচে আনুমানিক বয়স লিখুন।',
    "Only if member lives outside this household's village": 'শুধু যদি সদস্য এই পরিবারের গ্রামের বাইরে থাকেন',
    'Leave blank if same village': 'একই গ্রাম হলে ফাঁকা রাখুন',
    'OTP verification required': 'OTP যাচাই প্রয়োজন',
    'Adding to': 'যুক্ত হচ্ছে',
    '👪 Household Members': '👪 পরিবারের সদস্য',
    'Household Created': 'পরিবার তৈরি হয়েছে',
    'Household No.': 'পরিবার নং',
    'House No.': 'বাড়ি নং',
    'Total Members': 'মোট সদস্য',
    'Patient already registered': 'রোগী ইতিমধ্যে নিবন্ধিত',
    'A member with this ID is already in your records. Registering again may create a duplicate.': 'এই আইডির একজন সদস্য ইতিমধ্যে আপনার রেকর্ডে আছেন। আবার নিবন্ধন করলে ডুপ্লিকেট তৈরি হতে পারে।',
    'View record': 'রেকর্ড দেখুন',
    'Failed to start visit': 'ভিজিট শুরু করা যায়নি',
    'First visit for this patient': 'এই রোগীর প্রথম ভিজিট',
    'Also in this household': 'এই পরিবারেও আছেন',
    'Starting...': 'শুরু হচ্ছে...',
    'today': 'আজ',
    'yesterday': 'গতকাল',
    'Pre-Visit Briefing': 'ভিজিট-পূর্ব ব্রিফিং',
    'AI-generated briefing based on patient history': 'রোগীর ইতিহাসের ভিত্তিতে এআই-তৈরি ব্রিফিং',
    'AI briefing unavailable — check patient record manually.': 'এআই ব্রিফিং উপলব্ধ নেই — রোগীর রেকর্ড নিজে দেখুন।',
    'Conversation Guide': 'কথোপকথন গাইড',
    "Personalised for this patient's programmes and history": 'এই রোগীর প্রোগ্রাম ও ইতিহাসের জন্য ব্যক্তিগতকৃত',
    'Conversation guide unavailable.': 'কথোপকথন গাইড উপলব্ধ নেই।',
    'Begin the Consultation': 'পরামর্শ শুরু করুন',
    'Ask the patient how they are feeling — the AI Scribe will start listening': 'রোগীকে জিজ্ঞাসা করুন কেমন লাগছে — এআই স্ক্রাইব শোনা শুরু করবে',
    'Ask the patient how she is feeling today and begin the consultation.': 'রোগীকে আজ কেমন লাগছে জিজ্ঞাসা করুন এবং পরামর্শ শুরু করুন।',
    'Ambient AI Scribe': 'অ্যাম্বিয়েন্ট এআই স্ক্রাইব',
    'Automatically transcribes and structures clinical information as you speak.': 'আপনি কথা বলার সাথে সাথে স্বয়ংক্রিয়ভাবে ক্লিনিকাল তথ্য লিখে সাজায়।',
    'Auto-fill Assessment': 'স্বয়ংক্রিয় মূল্যায়ন পূরণ',
    'Relevant fields in the assessment form are populated from the conversation.': 'কথোপকথন থেকে মূল্যায়ন ফর্মের প্রাসঙ্গিক ঘর পূরণ হয়।',
    'You Review Everything': 'আপনি সবকিছু পর্যালোচনা করেন',
    'All AI suggestions are proposals — you accept or edit before submitting.': 'সব এআই পরামর্শ প্রস্তাব — জমা দেওয়ার আগে আপনি গ্রহণ বা সম্পাদনা করেন।',
    'Begin Assessment': 'মূল্যায়ন শুরু করুন',
    'Skip briefing': 'ব্রিফিং এড়িয়ে যান',
    'Visit Details': 'ভিজিটের বিবরণ',
    'Visit': 'ভিজিট',
    'Visit Information': 'ভিজিটের তথ্য',
    'Service': 'সেবা',
    'General Visit': 'সাধারণ ভিজিট',
    'Visit Date': 'ভিজিটের তারিখ',
    'Review Date': 'পর্যালোচনার তারিখ',
    'Visit Number': 'ভিজিট নম্বর',
    'Status': 'অবস্থা',
    'Visit Type': 'ভিজিটের ধরন',
    'Patient Status': 'রোগীর অবস্থা',
    'Encounter ID': 'এনকাউন্টার আইডি',
    'Presenting Complaints': 'উপস্থাপিত অভিযোগ',
    'Systemic Examinations': 'সিস্টেমিক পরীক্ষা',
    'Obstetric Examinations': 'প্রসূতি পরীক্ষা',
    'Complaints': 'অভিযোগ',
    'Physical Examinations': 'শারীরিক পরীক্ষা',
    'Comorbidities': 'সহ-রোগ',
    'Complications': 'জটিলতা',
    'Investigations': 'পরীক্ষা-নিরীক্ষা',
    'Clinical Notes': 'ক্লিনিকাল নোট',
    'Notes': 'নোট',
    'Visit History': 'ভিজিটের ইতিহাস',
    'Unknown': 'অজানা',
    'Prescriptions': 'প্রেসক্রিপশন',
    'Unknown Medication': 'অজানা ওষুধ',
    'Dosage': 'মাত্রা',
    'Frequency': 'ফ্রিকোয়েন্সি',
    'Duration': 'স্থিতিকাল',
    'Instructions': 'নির্দেশনা',
    'Provider Information': 'প্রদানকারীর তথ্য',
    'Provider': 'প্রদানকারী',
    'Facility': 'প্রতিষ্ঠান',
    'Labour & Delivery': 'প্রসব',
    'Delivery Type': 'প্রসবের ধরন',
    'Delivery At': 'প্রসব স্থান',
    'Delivery By': 'প্রসব করিয়েছেন',
    'Delivery Status': 'প্রসবের অবস্থা',
    'Delivery Date/Time': 'প্রসবের তারিখ/সময়',
    'Labour Onset': 'প্রসব বেদনা শুরু',
    'Neonate / Baby': 'নবজাতক / শিশু',
    'Mother Alive': 'মা জীবিত',
    'Yes': 'হ্যাঁ',
    'No': 'না',
    'Neonate Outcome': 'নবজাতকের ফলাফল',
    'State of Baby': 'শিশুর অবস্থা',
    'Birth Weight': 'জন্ম ওজন',
    'Breast Condition': 'স্তনের অবস্থা',
    'Breast Notes': 'স্তন সম্পর্কিত নোট',
    'Involution of Uterus': 'জরায়ু সংকোচন',
    'Signs': 'লক্ষণ',
    'Additional Details': 'অতিরিক্ত বিবরণ',
    'AI Assistant': 'এআই সহায়ক',
    'Ask a clinical question…': 'একটি ক্লিনিকাল প্রশ্ন করুন…',
    'Could not reach the assistant. Check your connection.': 'সহায়কে পৌঁছানো যায়নি। সংযোগ যাচাই করুন।',
    'How do I measure MUAC?': 'MUAC কীভাবে মাপব?',
    'ANC danger signs?': 'ANC বিপদ চিহ্ন কী কী?',
    'NCD medication adherence tips': 'NCD ওষুধ সেবনের টিপস',
    'When to refer a child?': 'কখন শিশুকে রেফার করব?',
    'FINDRISC score interpretation': 'FINDRISC স্কোরের ব্যাখ্যা',
    'Ask me anything': 'যা জানতে চান জিজ্ঞাসা করুন',
    'Clinical guidance, protocol reminders, and care tips — always at hand.': 'ক্লিনিকাল পরামর্শ, প্রোটোকল স্মরণিকা ও সেবার টিপস — সবসময় হাতের কাছে।',
    'Powered by Gemini · For clinical guidance only': 'Gemini দ্বারা পরিচালিত · শুধুমাত্র ক্লিনিকাল পরামর্শের জন্য',
    'Ask AI': 'এআইকে জিজ্ঞাসা করুন',
    'You might also ask:': 'আপনি এটাও জিজ্ঞাসা করতে পারেন:',
    'Tap to speak': 'কথা বলতে চাপুন',
    'Tap to stop': 'থামাতে চাপুন',
    'Listening…': 'শোনা হচ্ছে…',
    'AI Coach': 'এআই কোচ',
    'How can I help you today? Ask me about patient counselling, clinical protocols, or SPICE.': 'আজ আমি কীভাবে সাহায্য করতে পারি? রোগীর কাউন্সেলিং, ক্লিনিকাল প্রোটোকল বা SPICE নিয়ে জিজ্ঞাসা করুন।',
    'Online': 'অনলাইন',
    'Clear chat history': 'চ্যাট ইতিহাস পরিষ্কার করুন',
    'Others in this household': 'এই পরিবারের অন্যরা',
    'Check if any family members need care today.': 'পরিবারের কারও আজ সেবা প্রয়োজন কিনা দেখুন।',
    'No other household members need a visit.': 'পরিবারের অন্য কোনো সদস্যের ভিজিট প্রয়োজন নেই।',
    'View patient': 'রোগী দেখুন',
    'Done — go to home': 'সম্পন্ন — হোমে যান',
    'Overdue': 'বাকি পড়েছে',
    'Due today': 'আজ বাকি',
    'Due soon': 'শীঘ্রই বাকি',
    'Select Household': 'পরিবার নির্বাচন করুন',
    'Choose the household to link this member to': 'এই সদস্যকে যুক্ত করার জন্য পরিবার নির্বাচন করুন',
    'Search by name, house number, or village...': 'নাম, বাড়ি নম্বর, বা গ্রাম দিয়ে খুঁজুন...',
    'households in your catchment': 'আপনার এলাকার পরিবার',
    'No households found': 'কোনো পরিবার পাওয়া যায়নি',
    'Link & Enrol': 'যুক্ত করুন ও নিবন্ধন করুন',
    'Unknown family': 'অজানা পরিবার',
    'members': 'সদস্য',
    'Selected household': 'নির্বাচিত পরিবার',
    'Link & Enrol Member': 'সদস্য যুক্ত করুন ও নিবন্ধন করুন',
    'Submitting…': 'জমা হচ্ছে…',
    'Member linked successfully': 'সদস্য সফলভাবে যুক্ত হয়েছে',
    'Could not link member': 'সদস্য যুক্ত করা যায়নি',
    'Vaccination': 'টিকাদান',
    'Date of birth not available — cannot compute schedule.': 'জন্ম তারিখ নেই — সময়সূচি তৈরি করা যাচ্ছে না।',
    'Given': 'দেওয়া হয়েছে',
    'Due now': 'এখন বাকি',
    'Upcoming': 'আসন্ন',
    'Not yet due': 'এখনও বাকি নয়',
    'Update Status →': 'অবস্থা আপডেট করুন →',
    'Vaccines due at this milestone': 'এই পর্যায়ে বাকি থাকা টিকা',
    'Date Administered': 'প্রদানের তারিখ',
    'Notes (Optional)': 'নোট (ঐচ্ছিক)',
    'e.g. Child was well, no adverse reaction…': 'যেমন, শিশু ভালো ছিল, কোনো প্রতিক্রিয়া হয়নি…',
    'Mark as Completed': 'সম্পন্ন হিসেবে চিহ্নিত করুন',
    'Done → Continue Visit': 'সম্পন্ন → ভিজিট চালিয়ে যান',
    'Child Assessment': 'শিশু মূল্যায়ন',
    'Does the child have any congenital defect?': 'শিশুর কোনো জন্মগত সমস্যা আছে?',
    'kg': 'কেজি',
    'e.g. 6.5': 'যেমন ৬.৫',
    'Is the child breastfeeding?': 'শিশু বুকের দুধ খায়?',
    'In the past 24 hours, was the child given additional food?': 'গত ২৪ ঘণ্টায় শিশুকে বাড়তি খাবার দেওয়া হয়েছে?',
    'Has the child received vaccines?': 'শিশু টিকা পেয়েছে?',
    'Has the child taken deworming medicine?': 'শিশু কৃমিনাশক ওষুধ খেয়েছে?',
    'Any Illness/Complications?': 'কোনো অসুস্থতা/জটিলতা আছে?',
    'If any complication, specify': 'কোনো জটিলতা থাকলে উল্লেখ করুন',
    'Has referral been made?': 'রেফার করা হয়েছে?',
    'Referral place': 'রেফারেল স্থান',
    '💉  Vaccination  →': '💉  টিকাদান  →',
    'Care Coordination Alerts': 'কেয়ার কোঅর্ডিনেশন সতর্কতা',
    'Powered by CCE · Care Coordination Engine': 'CCE দ্বারা পরিচালিত · কেয়ার কোঅর্ডিনেশন ইঞ্জিন',
    'CCE tracks every patient after referral and triggers alerts when SLAs are breached — so no patient is lost between SK and facility.': 'CCE রেফারেলের পর প্রতিটি রোগীকে ট্র্যাক করে এবং SLA লঙ্ঘন হলে সতর্কতা দেয় — যাতে এসকে ও প্রতিষ্ঠানের মাঝে কোনো রোগী হারিয়ে না যায়।',
    'Search by name or village…': 'নাম বা গ্রাম দিয়ে খুঁজুন…',
    'No alerts match your search': 'আপনার খোঁজের সাথে মিলে এমন কোনো সতর্কতা নেই',
    'Try a different patient name or village.': 'অন্য রোগীর নাম বা গ্রাম দিয়ে চেষ্টা করুন।',
    'All referrals on track': 'সব রেফারেল ঠিকমতো চলছে',
    'No SLA breaches. Every referred patient is accounted for between SK and facility.': 'কোনো SLA লঙ্ঘন নেই। প্রতিটি রেফার করা রোগীর হিসাব এসকে ও প্রতিষ্ঠানের মধ্যে রাখা আছে।',
    'Call family': 'পরিবারকে কল করুন',
    'Update status': 'অবস্থা আপডেট করুন',
    'Locate': 'খুঁজে বের করুন',
    'Check in': 'চেক ইন করুন',
    'No phone number on file for this patient': 'এই রোগীর কোনো ফোন নম্বর নেই',
    'No location on file for this patient': 'এই রোগীর কোনো অবস্থান নেই',
    'Could not open the dialer': 'ডায়ালার খোলা যায়নি',
    'Where is the patient now?': 'রোগী এখন কোথায়?',
    'Not yet left home': 'এখনও বাড়ি থেকে যায়নি',
    'On the way to facility': 'প্রতিষ্ঠানের দিকে যাচ্ছে',
    'Arrived at facility': 'প্রতিষ্ঠানে পৌঁছেছে',
    'Seen by clinician / treated': 'চিকিৎসক দেখেছেন / চিকিৎসা হয়েছে',
    'Discharged (recovered)': 'ছাড়পত্র (সুস্থ হয়েছে)',
    'Add a barrier tag (optional)': 'একটি বাধা ট্যাগ যুক্ত করুন (ঐচ্ছিক)',
    'Transport': 'যাতায়াত',
    'Cost': 'খরচ',
    'Family': 'পরিবার',
    'Distance': 'দূরত্ব',
    'Save update': 'আপডেট সংরক্ষণ করুন',
    'Saves offline · syncs on next cycle': 'অফলাইনে সংরক্ষিত হয় · পরের সাইকেলে সিঙ্ক হয়',
    'Referral status updated': 'রেফারেলের অবস্থা আপডেট হয়েছে',
    "Select the patient's current status": 'রোগীর বর্তমান অবস্থা নির্বাচন করুন',
    'Update patient status': 'রোগীর অবস্থা আপডেট করুন',
    'CCE will sync this update to the facility and supervisor': 'CCE এই আপডেট প্রতিষ্ঠান ও সুপারভাইজারের কাছে সিঙ্ক করবে',
    'Patient reached facility': 'রোগী প্রতিষ্ঠানে পৌঁছেছে',
    'Unable to travel — transport issue': 'যাতায়াত করতে পারছেন না — যাতায়াতের সমস্যা',
    'Patient refused referral': 'রোগী রেফারেল প্রত্যাখ্যান করেছেন',
    'Patient recovered at home': 'রোগী বাড়িতে সুস্থ হয়েছেন',
    'Other — add note': 'অন্যান্য — নোট যুক্ত করুন',
    'Confirm & sync to CCE': 'নিশ্চিত করুন ও CCE-তে সিঙ্ক করুন',
    'Describe what happened…': 'কী হয়েছে তা লিখুন…',
    'Please add a note before saving': 'সংরক্ষণের আগে একটি নোট যুক্ত করুন',
    'Log call': 'কল লগ করুন',
    'Log follow-up call': 'ফলো-আপ কল লগ করুন',
    'How did the call go?': 'কল কেমন হয়েছে?',
    'Reached — successful': 'পৌঁছানো গেছে — সফল',
    'Could not reach': 'পৌঁছানো যায়নি',
    'Wrong number': 'ভুল নম্বর',
    'Note (optional)': 'নোট (ঐচ্ছিক)',
    'e.g. no answer, will retry tomorrow': 'যেমন, উত্তর দেননি, কাল আবার চেষ্টা করব',
    'Save call': 'কল সংরক্ষণ করুন',
    'Call logged — will sync on next cycle': 'কল লগ হয়েছে — পরের সাইকেলে সিঙ্ক হবে',
    'Schedule': 'সময়সূচি',
    'Follow-up scheduled — will sync on next cycle': 'ফলো-আপ নির্ধারিত হয়েছে — পরের সাইকেলে সিঙ্ক হবে',
    'Could not schedule the follow-up': 'ফলো-আপ নির্ধারণ করা যায়নি',
    'Select the call outcome': 'কলের ফলাফল নির্বাচন করুন',
    'Wrong number or exhausted attempts will close this follow-up.': 'ভুল নম্বর বা সব চেষ্টা শেষ হলে এই ফলো-আপ বন্ধ হবে।',
    'Could not log the call': 'কল লগ করা যায়নি',
    'Add Services': 'সেবা যুক্ত করুন',
    'Add the health programmes this person needs. Tap a programme to select it.': 'এই ব্যক্তির প্রয়োজনীয় স্বাস্থ্য প্রোগ্রাম যুক্ত করুন। নির্বাচনের জন্য একটি প্রোগ্রাম চাপুন।',
    'PREGNANCY CARE': 'গর্ভাবস্থার সেবা',
    'CHRONIC CONDITIONS': 'দীর্ঘস্থায়ী রোগ',
    'CHILD HEALTH': 'শিশু স্বাস্থ্য',
    '⚠ Select "Pregnant Woman" first to unlock ANC': '⚠ ANC আনলক করতে আগে "গর্ভবতী মা" নির্বাচন করুন',
    '⚠ Select "Pregnant Woman" first to unlock PNC': '⚠ PNC আনলক করতে আগে "গর্ভবতী মা" নির্বাচন করুন',
    'No eligible programmes for this patient based on age and gender.': 'বয়স ও লিঙ্গের ভিত্তিতে এই রোগীর জন্য কোনো উপযুক্ত প্রোগ্রাম নেই।',
    'Programmes saved ✓': 'প্রোগ্রাম সংরক্ষিত হয়েছে ✓',
    'No services enrolled': 'কোনো সেবা নিবন্ধিত নয়',
    'Tap below to add health programmes for this patient.': 'এই রোগীর জন্য স্বাস্থ্য প্রোগ্রাম যুক্ত করতে নিচে চাপুন।',
    'Register Pregnancy': 'গর্ভধারণ নিবন্ধন করুন',
    'PREGNANCY DATES': 'গর্ভাবস্থার তারিখ',
    'Last Menstrual Period (LMP)': 'সর্বশেষ মাসিক তারিখ (LMP)',
    '* Required': '* আবশ্যক',
    'Tap to select date': 'তারিখ নির্বাচন করতে চাপুন',
    'Est. Due Date (EDD)': 'প্রত্যাশিত প্রসব তারিখ (EDD)',
    '⚠ LMP is less than 6 weeks ago. Only basic details saved — full risk screening at next visit.': '⚠ LMP ৬ সপ্তাহের কম আগে। শুধু মৌলিক তথ্য সংরক্ষিত হয়েছে — পরের ভিজিটে সম্পূর্ণ ঝুঁকি স্ক্রিনিং হবে।',
    'OBSTETRIC HISTORY': 'প্রসূতি ইতিহাস',
    'Gravida (total pregnancies)': 'গ্র্যাভিডা (মোট গর্ভধারণ)',
    'Parity (live births)': 'প্যারিটি (জীবিত জন্ম)',
    'First pregnancy': 'প্রথম গর্ভধারণ',
    'RISK SCREENING': 'ঝুঁকি স্ক্রিনিং',
    'Any existing conditions?': 'কোনো বিদ্যমান রোগ আছে?',
    'Hypertension / High BP': 'উচ্চ রক্তচাপ',
    'Previous C-section': 'পূর্বে সিজারিয়ান',
    'Previous complicated delivery': 'পূর্বে জটিল প্রসব',
    '🤰  Register Pregnancy': '🤰  গর্ভধারণ নিবন্ধন করুন',
    'Pregnancy registered ✓': 'গর্ভধারণ নিবন্ধিত হয়েছে ✓',
    'Please select the LMP date': 'LMP তারিখ নির্বাচন করুন',
    'LMP cannot be in the future': 'LMP ভবিষ্যতে হতে পারে না',
    '⚠ Gravida > 4 — multipara risk': '⚠ গ্র্যাভিডা > ৪ — বহু-প্রসবের ঝুঁকি',
    '1. How are you?': '১. আপনি কেমন আছেন?',
    '3. Summary': '৩. সারাংশ',
    'How is she feeling today? 🎙': 'আজ তার কেমন লাগছে? 🎙',
    'How is he feeling today? 🎙': 'আজ তার কেমন লাগছে? 🎙',
    'Tap and let her speak': 'চাপুন এবং তাকে কথা বলতে দিন',
    '🎙 Start': '🎙 শুরু করুন',
    'Search symptoms...': 'লক্ষণ খুঁজুন...',
    'Start Visit →': 'ভিজিট শুরু করুন →',
    'Select a service to continue': 'চালিয়ে যেতে একটি সেবা নির্বাচন করুন',
    "I have this patient's record. I'll answer only from their data — ask about their care, or tap an action below.": 'আমার কাছে এই রোগীর রেকর্ড আছে। আমি শুধু তার তথ্য থেকে উত্তর দিব — তার সেবা নিয়ে জিজ্ঞাসা করুন, বা নিচে একটি কাজ চাপুন।',
    'Ask about this patient...': 'এই রোগী নিয়ে জিজ্ঞাসা করুন...',
    '🔒 Answers limited to this patient': '🔒 উত্তর শুধু এই রোগীর জন্য সীমিত',
    'Ask AI about this patient': 'এই রোগী নিয়ে এআইকে জিজ্ঞাসা করুন',
    'Data Collection Consent': 'তথ্য সংগ্রহের সম্মতি',
    'Apon Sushashthya Health Programme': 'আপন সুস্বাস্থ্য স্বাস্থ্য প্রোগ্রাম',
    'Before we register this household, we need your permission to collect and use health information for the purpose of providing community healthcare services.': 'এই পরিবার নিবন্ধনের আগে, কমিউনিটি স্বাস্থ্যসেবা প্রদানের উদ্দেশ্যে স্বাস্থ্য তথ্য সংগ্রহ ও ব্যবহারের জন্য আমাদের আপনার অনুমতি প্রয়োজন।',
    'What we collect': 'আমরা যা সংগ্রহ করি',
    'We collect names, ages, health conditions, visit records, and contact details of household members enrolled in the UHIS Leapfrog programme.': 'আমরা UHIS Leapfrog প্রোগ্রামে নিবন্ধিত পরিবারের সদস্যদের নাম, বয়স, স্বাস্থ্য অবস্থা, ভিজিট রেকর্ড ও যোগাযোগের তথ্য সংগ্রহ করি।',
    'How we use it': 'আমরা এটি কীভাবে ব্যবহার করি',
    'Information is used by trained health workers to provide follow-up care, track programme outcomes, and improve community health services. It is never shared with third parties outside the programme.': 'তথ্য প্রশিক্ষিত স্বাস্থ্যকর্মীরা ফলো-আপ সেবা প্রদান, প্রোগ্রামের ফলাফল ট্র্যাক ও কমিউনিটি স্বাস্থ্যসেবা উন্নত করতে ব্যবহার করেন। এটি প্রোগ্রামের বাইরে কোনো তৃতীয় পক্ষের সাথে শেয়ার করা হয় না।',
    'Your rights': 'আপনার অধিকার',
    'You may withdraw consent at any time by contacting your village health worker. Data will be retained as required by national health regulations.': 'আপনি যেকোনো সময় আপনার গ্রাম স্বাস্থ্যকর্মীর সাথে যোগাযোগ করে সম্মতি প্রত্যাহার করতে পারেন। জাতীয় স্বাস্থ্য নিয়মাবলী অনুযায়ী তথ্য সংরক্ষিত থাকবে।',
    'I have read and understood the above. I give consent for health data collection for members of this household.': 'আমি উপরের বিষয়টি পড়েছি ও বুঝেছি। আমি এই পরিবারের সদস্যদের স্বাস্থ্য তথ্য সংগ্রহের জন্য সম্মতি দিচ্ছি।',
    'I Agree': 'আমি সম্মত',
    'Decline': 'প্রত্যাখ্যান করুন',
    'Without consent, household registration cannot be completed.': 'সম্মতি ছাড়া পরিবার নিবন্ধন সম্পন্ন করা যাবে না।',
    'Cancel registration': 'নিবন্ধন বাতিল করুন',
    'Go back': 'পেছনে যান',
    'ANC / Pregnancy': 'ANC / গর্ভাবস্থা',
    'Pre-eclampsia watch': 'প্রি-এক্লাম্পসিয়া পর্যবেক্ষণ',
    'Blood sugar': 'রক্তে শর্করা',
    'Growth monitoring': 'বৃদ্ধি পর্যবেক্ষণ',
    'Postnatal recovery': 'প্রসবোত্তর সুস্থতা',
    'Newborn care': 'নবজাতকের সেবা',
    'General enrollment': 'সাধারণ নিবন্ধন',
    'Past illness': 'পূর্বের অসুস্থতা',
    'High-risk pregnancy': 'উচ্চ-ঝুঁকির গর্ভাবস্থা',
    'Emergency C-section': 'জরুরি সিজারিয়ান',
    'Congratulations on this pregnancy! Today we:\n• Registered you in the ANC programme\n• Measured your blood pressure and weight\n• Scheduled your next visit in 4 weeks\n\nRemember to:\n• Take your iron-folate tablet every day\n• Eat nutritious food — dal, eggs, leafy vegetables\n• Rest and avoid heavy lifting\n• Come immediately if you have heavy bleeding, severe headache, or blurred vision': 'আপনার গর্ভধারণে অভিনন্দন! আজ আমরা:\n• আপনাকে ANC প্রোগ্রামে নিবন্ধিত করেছি\n• আপনার রক্তচাপ ও ওজন মেপেছি\n• ৪ সপ্তাহ পরে আপনার পরের ভিজিট নির্ধারণ করেছি\n\nমনে রাখবেন:\n• প্রতিদিন আয়রন-ফলিক ট্যাবলেট খান\n• পুষ্টিকর খাবার খান — ডাল, ডিম, শাক-সবজি\n• বিশ্রাম নিন এবং ভারী কাজ এড়িয়ে চলুন\n• অতিরিক্ত রক্তক্ষরণ, তীব্র মাথাব্যথা বা ঝাপসা দৃষ্টি হলে এখনই আসুন',
    'Video consultation with a doctor will be available here.\nThe SK can initiate a call directly from a completed visit.': 'এখানে ডাক্তারের সাথে ভিডিও পরামর্শ পাওয়া যাবে।\nএসকে সম্পন্ন ভিজিট থেকে সরাসরি কল শুরু করতে পারবেন।',
    'Clinical guidance, protocol reminders,\nand care tips — always at hand.': 'ক্লিনিকাল পরামর্শ, প্রোটোকল স্মরণিকা,\nও সেবার টিপস — সবসময় হাতের কাছে।',
    '{part}, {name}': '{part}, {name}',
    'Scanning households {loaded}/{cap}…': 'পরিবার স্ক্যান হচ্ছে {loaded}/{cap}…',
    'Age {age}': 'বয়স {age}',
    'NID {nid}': 'এনআইডি {nid}',
    'No {no}': 'নং {no}',
    '{count} members': '{count} জন সদস্য',
    'Create a {len}-digit PIN': '{len}-সংখ্যার পিন তৈরি করুন',
    'Enter your {len}-digit PIN': 'আপনার {len}-সংখ্যার পিন লিখুন',
    'Use {len}-digit PIN': '{len}-সংখ্যার পিন ব্যবহার করুন',
    '{n} attempts remaining': '{n} বার চেষ্টা বাকি',
    '{entity} {count}': '{entity} {count}',
    'Data as of {relative}': '{relative} অনুযায়ী তথ্য',
    'Data as of {m}m ago': '{m} মিনিট আগের তথ্য',
    'Data as of {h}h ago': '{h} ঘণ্টা আগের তথ্য',
    'Data as of {d}d ago': '{d} দিন আগের তথ্য',
    '{len}-Digit Backup PIN': '{len}-সংখ্যার ব্যাকআপ পিন',
    '⚠ {reason}': '⚠ {reason}',
    '{patient} — {reason}': '{patient} — {reason}',
    '#{no}': '#{no}',
    '{done} / {total}': '{done} / {total}',
    '{percent}%': '{percent}%',
    '{count} {status}': '{count} {status}',
    '#{number}': '#{number}',
    'STEP 1 OF 3 · AI TRIAGE · {programme}': 'ধাপ ১ এর ৩ · এআই ট্রায়াজ · {programme}',
    '⚠ {name} · current concerns flagged — act today if symptoms persist': '⚠ {name} · বর্তমান সমস্যা চিহ্নিত — লক্ষণ থাকলে আজই ব্যবস্থা নিন',
    'Select {label}': '{label} নির্বাচন করুন',
    'Deselect {label}': '{label} বাতিল করুন',
    'Enrolled {label} — tap to include or exclude from this visit': 'নিবন্ধিত {label} — এই ভিজিটে অন্তর্ভুক্ত বা বাদ দিতে চাপুন',
    'Section {current} of {total} — {sectionTitle}': 'বিভাগ {current}-এর {total} — {sectionTitle}',
    '{done} of {total} programmes synced': '{done}-এর মধ্যে {total}টি প্রোগ্রাম সিঙ্ক হয়েছে',
    '{n} selected': '{n}টি নির্বাচিত',
    '{programmeName} was recommended because: {trigger}.\n\nSkipping will create a follow-up task so it surfaces next visit.': '{programmeName} সুপারিশ করা হয়েছিল কারণ: {trigger}।\n\nএড়িয়ে গেলে একটি ফলো-আপ কাজ তৈরি হবে যা পরের ভিজিটে দেখা যাবে।',
    'Assessment {current} of {total} — {programme}': 'মূল্যায়ন {current}-এর {total} — {programme}',
    '"{symptomLabel}" is associated with the {programmeNames} program. Adding it will include the {programmeNames} assessment in this visit.': '"{symptomLabel}" {programmeNames} প্রোগ্রামের সাথে সম্পর্কিত। এটি যুক্ত করলে এই ভিজিটে {programmeNames} মূল্যায়ন অন্তর্ভুক্ত হবে।',
    '{pct}% confidence': '{pct}% আত্মবিশ্বাস',
    'Add {programmeTag} assessment?': '{programmeTag} মূল্যায়ন যুক্ত করবেন?',
    'Skip {programmeTag} for this visit?': 'এই ভিজিটে {programmeTag} এড়িয়ে যাবেন?',
    '{programmeTag} added to this visit': '{programmeTag} এই ভিজিটে যুক্ত হয়েছে',
    '{programmeTag} removed from this visit': '{programmeTag} এই ভিজিট থেকে বাদ দেওয়া হয়েছে',
    'New · Triggered by {reason}': 'নতুন · {reason} দ্বারা সক্রিয়',
    'Done · +{pts} pts': 'সম্পন্ন · +{pts} পয়েন্ট',
    'Complete {n} more to unlock': 'আনলক করতে আরও {n}টি সম্পন্ন করুন',
    '{n} min read': '{n} মিনিটের পাঠ',
    '{correct} / {total} correct': '{correct}-এর {total} সঠিক',
    '{current} of {total}': '{current}-এর {total}',
    'Question {current} of {total}': 'প্রশ্ন {current}-এর {total}',
    'AI sees a trend across her {n} visits': 'এআই তার {n}টি ভিজিটে একটি ধারা দেখছে',
    'V{n}': 'V{n}',
    '{cm} cm lag ⚠️': '{cm} সেমি পিছিয়ে ⚠️',
    '{cm} cm ahead': '{cm} সেমি এগিয়ে',
    'Expected ~{gestWeeks} cm at {gestWeeks} wks': '{gestWeeks} সপ্তাহে প্রত্যাশিত ~{gestWeeks} সেমি',
    'You completed {pct}% more visits than the Manikganj Sadar area average this week.': 'এই সপ্তাহে আপনি মানিকগঞ্জ সদর এলাকার গড়ের চেয়ে {pct}% বেশি ভিজিট সম্পন্ন করেছেন।',
    'You completed {pct}% more visits than the Manikganj Sadar area average this month.': 'এই মাসে আপনি মানিকগঞ্জ সদর এলাকার গড়ের চেয়ে {pct}% বেশি ভিজিট সম্পন্ন করেছেন।',
    '✓ NID number captured: {number}': '✓ এনআইডি নম্বর নেওয়া হয়েছে: {number}',
    '✓ Already registered as {name} — details loaded from server': '✓ ইতিমধ্যে {name} নামে নিবন্ধিত — সার্ভার থেকে তথ্য লোড হয়েছে',
    'Already registered as {name}': 'ইতিমধ্যে {name} নামে নিবন্ধিত',
    '{age} years': '{age} বছর',
    '{days} days ago': '{days} দিন আগে',
    '{weeks} weeks ago': '{weeks} সপ্তাহ আগে',
    'Last seen {timeAgo} — {programme}': 'সর্বশেষ দেখা {timeAgo} — {programme}',
    'Update — {patientName}': 'আপডেট — {patientName}',
    'Select services for {name}': '{name}-এর জন্য সেবা নির্বাচন করুন',
    'For {name}': '{name}-এর জন্য',
    'Age {age} · Normal age for pregnancy': 'বয়স {age} · গর্ভধারণের জন্য স্বাভাবিক বয়স',
    '⚠ Age {age} · Under 18 — high risk': '⚠ বয়স {age} · ১৮-এর নিচে — উচ্চ ঝুঁকি',
    '⚠ Age {age} · Over 35 — high risk': '⚠ বয়স {age} · ৩৫-এর বেশি — উচ্চ ঝুঁকি',
    'Ask about {name}': '{name} নিয়ে জিজ্ঞাসা করুন',
}
