#!/usr/bin/env python3
"""
Publishes UHIS Leapfrog Mobile developer docs to Confluence.

Pages are generated by PARSING the actual Dart source files so every new
section, DB table, CDS alert, or programme enum value automatically shows
up in Confluence on the next push to main — no manual doc editing needed.

Required env vars:
  CONFLUENCE_BASE_URL       e.g. https://mdtlabs.atlassian.net
  CONFLUENCE_EMAIL          Atlassian account email
  CONFLUENCE_API_TOKEN      Atlassian API token
  CONFLUENCE_SPACE_KEY      Space key, e.g. UNL
  CONFLUENCE_PARENT_PAGE_ID Parent page numeric ID, e.g. 712540457
"""

import os, re, subprocess, datetime, sys
from pathlib import Path

try:
    from atlassian import Confluence
except ImportError:
    print("pip install atlassian-python-api", file=sys.stderr)
    sys.exit(1)

# ---------------------------------------------------------------------------
# Config
# ---------------------------------------------------------------------------
BASE_URL  = os.environ["CONFLUENCE_BASE_URL"]
EMAIL     = os.environ["CONFLUENCE_EMAIL"]
TOKEN     = os.environ["CONFLUENCE_API_TOKEN"]
SPACE     = os.environ.get("CONFLUENCE_SPACE_KEY", "UNL")
PARENT_ID = os.environ.get("CONFLUENCE_PARENT_PAGE_ID", "712540457")
TODAY     = datetime.date.today().isoformat()
REPO_ROOT = Path(__file__).parent.parent

conf = Confluence(url=BASE_URL, username=EMAIL, password=TOKEN, cloud=True)


# ---------------------------------------------------------------------------
# Confluence storage-format helpers
# ---------------------------------------------------------------------------
def h(level, text):
    return f"<h{level}>{text}</h{level}>"

def p(text):
    return f"<p>{text}</p>"

def ul(items):
    return "<ul>" + "".join(f"<li>{i}</li>" for i in items) + "</ul>"

def code(content, language="bash"):
    return (
        f'<ac:structured-macro ac:name="code" ac:schema-version="1">'
        f'<ac:parameter ac:name="language">{language}</ac:parameter>'
        f"<ac:plain-text-body><![CDATA[{content}]]></ac:plain-text-body>"
        f"</ac:structured-macro>"
    )

def table(headers, rows):
    head = "<tr>" + "".join(f"<th><strong>{c}</strong></th>" for c in headers) + "</tr>"
    body = "".join(
        "<tr>" + "".join(f"<td>{c}</td>" for c in row) + "</tr>"
        for row in rows
    )
    return f"<table>{head}{body}</table>"

def info(text):
    return (
        f'<ac:structured-macro ac:name="info" ac:schema-version="1">'
        f"<ac:rich-text-body><p>{text}</p></ac:rich-text-body>"
        f"</ac:structured-macro>"
    )

def warning(text):
    return (
        f'<ac:structured-macro ac:name="warning" ac:schema-version="1">'
        f"<ac:rich-text-body><p>{text}</p></ac:rich-text-body>"
        f"</ac:structured-macro>"
    )

def note(text):
    return (
        f'<ac:structured-macro ac:name="note" ac:schema-version="1">'
        f"<ac:rich-text-body><p>{text}</p></ac:rich-text-body>"
        f"</ac:structured-macro>"
    )


# ---------------------------------------------------------------------------
# Source parsers — read Dart files, extract structured data
# ---------------------------------------------------------------------------

def parse_sections():
    """
    Parse section_registry.dart → list of (sectionId, programmes, priority, fieldCount).
    Walks through FormSection( blocks and extracts the three header fields.
    """
    path = REPO_ROOT / "lib/features/visit/composer/section_registry.dart"
    src = path.read_text()

    # Collect (sectionId, programmes, priority) triples
    # Pattern: after FormSection( we expect sectionId, programmes, priority in that order
    blocks = re.findall(
        r"FormSection\(\s*sectionId:\s*'([^']+)',\s*programmes:\s*\{([^}]+)\},\s*priority:\s*(\d+),",
        src,
    )

    # Count FieldDef occurrences per section block
    section_src_blocks = re.split(r"FormSection\(", src)[1:]

    results = []
    for i, (sid, progs_raw, prio) in enumerate(blocks):
        progs = re.sub(r"Programme\.", "", progs_raw).replace(" ", "")
        # count FieldDef entries in this block (up to next FormSection)
        block_text = section_src_blocks[i] if i < len(section_src_blocks) else ""
        field_count = block_text.count("FieldDef(")
        results.append((sid, progs, int(prio), field_count))

    results.sort(key=lambda x: x[2])
    return results


def parse_db_tables():
    """
    Parse app_database.dart → (schema_version, table_names, migration_notes).
    """
    path = REPO_ROOT / "lib/core/db/app_database.dart"
    src = path.read_text()

    version = re.search(r"static const int schemaVersion = (\d+)", src)
    schema_version = int(version.group(1)) if version else "?"

    tables = re.findall(r"static const String table\w+ = '([^']+)'", src)

    # Migration notes: parse comment lines after each `if (from < N)` guard
    migration_rows = []
    for m in re.finditer(r"if \(from < (\d+)\) \{[^\n]*\n\s*// (.+)", src):
        ver = m.group(1)
        note_text = m.group(2).strip()
        migration_rows.append((f"v{ver}", note_text))

    return schema_version, tables, migration_rows


def parse_cds_alerts():
    """
    Parse cds_rules.dart → list of (alertId, severity, action).
    """
    path = REPO_ROOT / "lib/features/visit/composer/cds_rules.dart"
    src = path.read_text()

    # Find CdsAlert(...) blocks and extract alertId, severity, action
    blocks = re.findall(
        r"CdsAlert\(\s*alertId:\s*'([^']+)',\s*severity:\s*CdsSeverity\.(\w+),.*?action:\s*CdsAction\.(\w+)",
        src,
        re.DOTALL,
    )
    # Deduplicate (some alerts appear in both const and dynamic form)
    seen = set()
    results = []
    for alert_id, severity, action in blocks:
        if alert_id not in seen and alert_id != "alertId":
            seen.add(alert_id)
            results.append((alert_id, severity, action))
    return results


def parse_programmes():
    """
    Parse programme.dart → list of programme enum values (excluding 'unknown').
    """
    path = REPO_ROOT / "lib/core/models/programme.dart"
    src = path.read_text()
    # Enum body is between the first { and the first ;
    enum_body = re.search(r"enum Programme \{([^}]+)\}", src)
    if not enum_body:
        return []
    values = re.findall(r"^\s+(\w+),?$", enum_body.group(1), re.MULTILINE)
    return [v for v in values if v not in ("unknown",)]


def parse_pubspec():
    """
    Parse pubspec.yaml → (app_version, key_deps dict).
    """
    path = REPO_ROOT / "pubspec.yaml"
    src = path.read_text()

    version = re.search(r"^version:\s*(.+)", src, re.MULTILINE)
    app_version = version.group(1).strip() if version else "?"

    key_deps = {}
    for pkg in ["flutter_secure_storage", "go_router", "provider",
                "sqflite_sqlcipher", "atlassian_python_api"]:
        m = re.search(rf"^\s+{re.escape(pkg)}:\s*(.+)", src, re.MULTILINE)
        if m:
            key_deps[pkg] = m.group(1).strip()

    return app_version, key_deps


def parse_cdss_algorithms():
    """
    Parse lib/core/cdss/ → list of (class_name, trigger_condition) per calculator.
    """
    cdss_dir = REPO_ROOT / "lib/core/cdss"
    results = []
    for dart_file in sorted(cdss_dir.glob("*_calculator.dart")):
        src = dart_file.read_text()
        cls = re.search(r"class (\w+Calculator)", src)
        # Look for the trigger condition in comments or logic
        trigger = re.search(r"trigger\s*=\s*([^;]+);", src)
        if cls:
            trigger_val = trigger.group(1).strip() if trigger else "—"
            results.append((cls.group(1), trigger_val))
    return results


def parse_gorouter_routes():
    """
    Parse app_router.dart or main.dart → routes list.
    Looks for GoRoute(path: '...') entries.
    """
    candidates = [
        REPO_ROOT / "lib/core/app_router.dart",
        REPO_ROOT / "lib/app_router.dart",
        REPO_ROOT / "lib/main.dart",
    ]
    for path in candidates:
        if path.exists():
            src = path.read_text()
            routes = re.findall(r"path:\s*'([^']+)'", src)
            if routes:
                return routes
    return []


# ---------------------------------------------------------------------------
# Upsert helper
# ---------------------------------------------------------------------------
def upsert(title, body, parent_id=PARENT_ID):
    existing = conf.get_page_by_title(space=SPACE, title=title)
    if existing:
        conf.update_page(page_id=existing["id"], title=title, body=body)
        print(f"  ✓ updated  → {title}")
    else:
        conf.create_page(space=SPACE, title=title, body=body, parent_id=parent_id)
        print(f"  ✓ created  → {title}")


# ---------------------------------------------------------------------------
# Page builders (use parsed data)
# ---------------------------------------------------------------------------

def page_home():
    schema_version, tables, _ = parse_db_tables()
    app_version, key_deps = parse_pubspec()
    programmes = parse_programmes()
    sections = parse_sections()

    return (
        h(1, "UHIS Leapfrog Mobile")
        + p(
            "Offline-first Flutter 3.x app for UHIS Shasthya Shebikas (frontline community health workers). "
            "Integrates AI-assisted triage, clinical decision support, household management, and a tiered mission dashboard."
        )
        + p(
            '<strong>Repository:</strong> '
            '<a href="https://github.com/Medtronic-LABS/uhis_lf_mobile">Medtronic-LABS/uhis_lf_mobile</a>'
        )
        + table(
            ["Item", "Value"],
            [
                ["App version", app_version],
                ["Framework", "Flutter 3.x · Dart"],
                ["State management", f"Provider {key_deps.get('provider', '')}"],
                ["Routing", f"GoRouter {key_deps.get('go_router', '')}"],
                ["Local DB", f"SQLCipher via sqflite_sqlcipher {key_deps.get('sqflite_sqlcipher', '')}"],
                ["Schema version", str(schema_version)],
                ["DB tables", str(len(tables))],
                ["Assessment sections", str(len(sections))],
                ["Active programmes", ", ".join(programmes)],
                ["Min Android SDK", "API 21 (Lollipop)"],
                ["Last published", TODAY],
            ],
        )
        + h(2, "Pages in this space")
        + table(
            ["Page", "What it covers"],
            [
                ["Developer Setup Guide", "Clone, configure, run locally, build for Android"],
                ["Architecture Overview", "Layers, state management, routing, reactive patterns"],
                ["Screens &amp; Navigation", "All screens, routes, composite scoring"],
                ["Offline Sync Model", "Sync protocol, entity ordering, conflict strategy"],
                ["Database Schema", f"All {len(tables)} SQLite tables, migration history v1–v{schema_version}"],
                ["Assessment &amp; CDS", f"3-step visit flow, {len(sections)} sections, CDS rules, CDSS algorithms"],
                ["API Reference", "All offline-service endpoints"],
                ["Changelog", "Auto-generated from git history"],
            ],
        )
        + note("This page and all sub-pages are auto-generated from source code on every push to main.")
    )


def page_developer_setup():
    app_version, key_deps = parse_pubspec()

    return (
        h(1, "Developer Setup Guide")
        + info(f"App version: <strong>{app_version}</strong>")
        + h(2, "Prerequisites")
        + table(
            ["Tool", "Version", "Install"],
            [
                ["Flutter", "3.x stable", '<a href="https://docs.flutter.dev/get-started/install">flutter.dev</a>'],
                ["Dart", "bundled with Flutter", "—"],
                ["Android Studio", "latest", '<a href="https://developer.android.com/studio">developer.android.com</a>'],
                ["Android SDK", "API 34", "via Android Studio SDK Manager"],
                ["Java", "17 (for Gradle)", "<code>brew install openjdk@17</code>"],
                ["adb", "any", "bundled with Android Studio"],
            ],
        )
        + h(2, "Clone &amp; configure")
        + code(
            "git clone https://github.com/Medtronic-LABS/uhis_lf_mobile.git\n"
            "cd uhis_lf_mobile\n"
            "flutter pub get"
        )
        + h(2, "Run on device / emulator")
        + code(
            "flutter devices\n\n"
            "# Android emulator (10.0.2.2 = host localhost)\n"
            "flutter run \\\n"
            "  --dart-define=API_BASE_URL=http://10.0.2.2:80 \\\n"
            "  --dart-define=PASSWORD_HASH_KEY=<hash_key>\n\n"
            "# Physical device on LAN\n"
            "flutter run \\\n"
            "  --dart-define=API_BASE_URL=http://192.168.1.100:80 \\\n"
            "  --dart-define=PASSWORD_HASH_KEY=<hash_key>"
        )
        + h(2, "Physical device (wireless ADB)")
        + p("Physical devices need your Mac LAN IP — <code>10.0.2.2</code> is emulator-only.")
        + code(
            "# 1. Find Mac LAN IP\n"
            "ifconfig | grep 'inet 192'\n\n"
            "# 2. Pair via Settings → Developer options → Wireless debugging\n"
            "adb pair 192.168.1.X:PORT\n"
            "adb connect 192.168.1.X:PORT\n\n"
            "# 3. Run\n"
            "flutter run \\\n"
            "  --dart-define=BASE_URL=http://192.168.1.X \\\n"
            "  --dart-define=PASSWORD_HASH_KEY=<hash_key>"
        )
        + h(2, "Build production APK")
        + code(
            "flutter build apk --debug \\\n"
            "  --dart-define=BASE_URL=https://spice-dev-backend.uhis.labsplatform.com \\\n"
            "  --dart-define=AI_SERVICE_URL=https://spice-dev-backend.uhis.labsplatform.com/ai-scribe \\\n"
            "  --dart-define=PASSWORD_HASH_KEY=<hash_key>\n\n"
            "adb install -r build/app/outputs/flutter-apk/app-debug.apk"
        )
        + h(2, "Environment variables")
        + table(
            ["--dart-define key", "Default", "Description"],
            [
                ["API_BASE_URL", "http://10.0.2.2:80", "Backend base URL"],
                ["PASSWORD_HASH_KEY", "(from team credential store)", "HmacSHA512 salt — never commit"],
            ],
        )
        + info("All config accessed via <code>lib/core/config/app_config.dart</code>. Never hardcode values in source.")
        + h(2, "Run tests")
        + code(
            "flutter test                         # all tests\n"
            "flutter test test/core/cdss/         # CDSS algorithm unit tests\n"
            "flutter test test/core/db/           # DAO tests (sqflite_ffi)"
        )
        + h(2, "Key dependencies")
        + table(
            ["Package", "Version", "Purpose"],
            [[pkg, ver, ""] for pkg, ver in key_deps.items()],
        )
        + h(2, "Common issues")
        + table(
            ["Problem", "Fix"],
            [
                ["<code>file is not a database</code> on first open", "Stale unencrypted DB — app auto-recovers (deletes + recreates)."],
                ["Login returns 401", "Hash key mismatch — check <code>--dart-define=PASSWORD_HASH_KEY</code>."],
                ["Sync hangs at 0%", "Backend unreachable — check <code>API_BASE_URL</code> and UHIS stack."],
                ["Gradle build fails", "Ensure Java 17 on PATH; run <code>./gradlew --stop</code> then retry."],
                ["<code>splashBg not found</code> (AAPT)", "<code>android/app/src/main/res/values/colors.xml</code> must contain <code>splashBg = #1B2B5E</code>."],
            ],
        )
    )


def page_architecture():
    programmes = parse_programmes()
    routes = parse_gorouter_routes()

    return (
        h(1, "Architecture Overview")
        + h(2, "Guiding principles")
        + ul([
            "<strong>Offline-first.</strong> Fully functional without network. All reads from local SQLite; writes local-first, sync opportunistically.",
            "<strong>Strict layering.</strong> UI ↔ state/domain ↔ repository/data ↔ transport. No business logic in widgets; no UI in repositories.",
            "<strong>Single truth per entity.</strong> Every constant, string, rule has exactly one home (<code>app_strings.dart</code>, <code>AppConfig</code>, dedicated DAO).",
        ])
        + h(2, "Layer diagram")
        + code(
            "┌─────────────────────────────────────────────────────┐\n"
            "│  UI Layer  (lib/features/*_screen.dart, widgets/)   │\n"
            "│  Flutter widgets · GoRouter · Provider consumers    │\n"
            "├─────────────────────────────────────────────────────┤\n"
            "│  State / Domain Layer                               │\n"
            "│  ChangeNotifier providers · *_repository.dart       │\n"
            "├─────────────────────────────────────────────────────┤\n"
            "│  Data Layer  (lib/core/db/*_dao.dart)               │\n"
            "│  SQLite DAOs · sqflite_sqlcipher                    │\n"
            "├─────────────────────────────────────────────────────┤\n"
            "│  Transport Layer  (lib/core/api/*_client.dart)      │\n"
            "│  Dart http · JWT bearer token                       │\n"
            "└─────────────────────────────────────────────────────┘\n"
            "         ↕ JSON over HTTP\n"
            "┌────────────────────────┐\n"
            "│  UHIS Backend          │\n"
            "│  offline-service :80   │\n"
            "└────────────────────────┘",
            language="text",
        )
        + h(2, "Active programmes")
        + p(f"Parsed from <code>lib/core/models/programme.dart</code> — {len(programmes)} active programmes:")
        + p(", ".join(f"<code>{pr}</code>" for pr in programmes))
        + h(2, "GoRouter routes")
        + (
            table(["Route"], [[r] for r in sorted(set(routes))])
            if routes
            else p("<em>(route file not found — add lib/core/app_router.dart)</em>")
        )
        + h(2, "Reactive dashboard pattern")
        + table(
            ["Method", "Notification", "When to use"],
            [
                ["<code>refresh()</code>", "fires _changes once after await", "Pull-to-refresh, post-sync"],
                ["<code>clearCache()</code>", "fires _changes immediately", "After visit completion"],
                ["<code>_invalidateCache()</code>", "silent — no notification", "Internal use before refresh()"],
            ],
        )
        + h(2, "Security model")
        + table(
            ["Concern", "Mechanism"],
            [
                ["DB encryption", "SQLCipher — per-device 256-bit key in Android EncryptedSharedPreferences (KeyStore-backed)"],
                ["API auth", "JWT bearer token in Authorization header · flutter_secure_storage"],
                ["Password hashing", "HmacSHA512(plaintext, hashKey) — hashKey injected at build time via --dart-define"],
                ["Session token", "Stored on device; password / hash never stored"],
                ["Stale DB recovery", "AppDatabase.open() catches SQLITE_NOTADB (26), deletes stale file, recreates encrypted DB"],
            ],
        )
    )


def page_screens():
    return (
        h(1, "Screens &amp; Navigation")
        + h(2, "Bottom navigation (persistent shell)")
        + table(
            ["Tab", "Route", "Screen", "Key features"],
            [
                ["0", "/", "MissionDashboardScreen", "Tiered queue, village chips, need filters, AI-sorted badge, pull-to-refresh"],
                ["1", "/patients", "HouseholdListScreen", "Members + Households tabs, village chips, search"],
                ["2", "/referrals", "ReferralListScreen", "Visits subtab (village + tier chips) + Referrals subtab (SLA breach countdown)"],
            ],
        )
        + h(3, "Band + Modifier Risk Model (Mission Dashboard)")
        + p("Worst single clinical finding sets the band. Modifiers rank within bands. Band and modifier are <strong>never shown to the SK</strong> — they drive sort order only.")
        + table(
            ["Band", "Label", "Status pill", "Examples"],
            [
                ["1", "Severe", "NOW (pulsing)", "BP ≥160/110, Hb &lt;7, one-sided weakness, danger sign"],
                ["2", "Moderate", "TODAY", "BP ≥140/90, Hb 7–9.9, fasting glucose 10–17.9"],
                ["3", "Mild", "TODAY / THIS WEEK", "BP 130–139/85–89, fasting glucose 6.1–6.9"],
                ["4", "Routine", "ROUTINE", "No active clinical trigger"],
            ],
        )
        + table(
            ["Modifier", "Meaning", "Sort position"],
            [
                ["a", "Additional risk (comorbidity, first pregnancy, age ≥60, GA ≥36 wks)", "Higher within band"],
                ["b", "Overdue — longer overdue ranks higher", "Below 'a' within band"],
            ],
        )
        + p("Sort sequence: <strong>1a → 1b → 1 → 2a → 2b → 2 → 3a → 3b → 3 → 4</strong>. Pregnant patients rank above non-pregnant in the same band.")
        + h(2, "Full-screen routes (outside shell)")
        + table(
            ["Route", "Screen", "Notes"],
            [
                ["/login", "LoginScreen", "Multipart POST → JWT in Authorization header (not cookie)"],
                ["/sync", "SyncProgressScreen", "Full sync on first login; warm sync on open"],
                ["/pin/setup", "PIN creation", "6-digit, stored hashed in flutter_secure_storage"],
                ["/pin/unlock", "PIN unlock", "Required after inactivity timeout"],
                ["/visit/:id/assessment", "SectionedAssessmentScreen", "3-step visit form (see Assessment & CDS)"],
                ["/patient/:id", "PatientDetailScreen", "Longitudinal history, risk trend, referrals"],
                ["/household/:id", "HouseholdDetailScreen", "Household composition, WASH indicators"],
            ],
        )
        + h(2, "Village chip pattern")
        + p("All 3 main screens use the same inline chip row:")
        + table(
            ["Property", "Value"],
            [
                ["Label", "WHICH VILLAGE ARE YOU VISITING? (app_strings.dart)"],
                ["Active color", "#1B2B5E (brand navy)"],
                ["Hidden when", "≤1 village in the dataset"],
                ["Dashboard + Tasks source", "MissionQueueItem.village"],
                ["Patients source", "MemberDao.getDistinctVillages()"],
            ],
        )
    )


def page_offline_sync():
    return (
        h(1, "Offline Sync Model")
        + h(2, "Sync types")
        + table(
            ["Type", "When", "What"],
            [
                ["Full sync", "First login after install / manual wipe", "Downloads all entities for SK's catchment"],
                ["Warm sync", "Every subsequent app open", "Incremental — entities updated since last sync timestamp"],
                ["Post-assessment push", "After completed visit", "Uploads assessment + encounter to server"],
            ],
        )
        + h(2, "Entity download order")
        + p("FK-safe order — parents before children:")
        + code(
            "1.  Households\n"
            "2.  Members           (FK → households)\n"
            "3.  Patients          (FK → members)\n"
            "4.  Patient programmes\n"
            "5.  Follow-ups\n"
            "6.  Immunisations\n"
            "7.  Assessments\n"
            "8.  Referrals\n"
            "9.  Referral status events\n"
            "10. Pregnancy snapshots\n"
            "11. Treatment presence\n"
            "12. AI suggestions cache",
            language="text",
        )
        + h(2, "Key endpoints")
        + table(
            ["Entity", "Method + Path"],
            [
                ["Login", "POST /offline-service/offline-sync/login (multipart: username, password)"],
                ["Households", "GET /offline-service/offline-sync/household-list"],
                ["Members", "GET /offline-service/offline-sync/member-list"],
                ["Patients", "GET /offline-service/offline-sync/patient-list"],
                ["Assessment history", "GET /offline-service/offline-sync/member-assessment-history"],
                ["Assessment upload", "POST /offline-service/offline-sync/assessment-upload"],
            ],
        )
        + h(2, "Tier inference")
        + p("When <code>nextFollowUpDate</code> is absent, <code>_inferDueAt()</code> uses:")
        + p("<code>due_at = last_visit_at + programme_default_interval</code>")
        + table(
            ["Programme", "Default interval"],
            [["NCD", "30 days"], ["ANC", "14 days"], ["PNC", "7 days"], ["TB", "30 days"], ["IMCI", "7 days"]],
        )
        + info("Patients without <code>last_visit_at</code> show as <strong>upcoming</strong> until first assessment history sync.")
        + h(2, "Offline write path")
        + code(
            "SK completes assessment\n"
            "  → local_assessments (sync_status='pending')\n"
            "  → on connectivity: SyncService.pushPending() uploads\n"
            "  → on success: sync_status='synced', fhir_id populated\n"
            "  → MissionDashboardRepository.clearCache() refreshes queue",
            language="text",
        )
    )


def page_database():
    schema_version, tables, migration_rows = parse_db_tables()

    col_rows = []
    # Pull CREATE TABLE column definitions from source
    db_src = (REPO_ROOT / "lib/core/db/app_database.dart").read_text()
    for tbl in tables:
        create_match = re.search(
            rf"CREATE TABLE \${{\w*}}{tbl}[^(]*\(([^;]+)\)\s*'''\s*\)",
            db_src,
            re.DOTALL,
        )
        if not create_match:
            create_match = re.search(
                rf"CREATE TABLE (?:\$\w+|\w+) \([^)]*id TEXT PRIMARY",
                db_src,
            )
        # Count columns via CREATE TABLE block
        tbl_block = re.search(
            rf"CREATE TABLE [^(]*{tbl}[^(]*\(([^)]+)\)",
            db_src,
            re.DOTALL,
        )
        col_count = tbl_block.group(1).count("\n") if tbl_block else "?"
        col_rows.append([f"<code>{tbl}</code>", str(col_count) if col_count != "?" else "?"])

    return (
        h(1, "Database Schema")
        + info(
            f"File: <code>uhis_offline.db</code> · Schema version: <strong>v{schema_version}</strong> · "
            f"Parsed from <code>lib/core/db/app_database.dart</code> · "
            f"SQLCipher encrypted, per-device key from Android KeyStore."
        )
        + h(2, f"Tables ({len(tables)} total)")
        + table(["Table", "~Columns"], col_rows)
        + h(2, "Migration history")
        + table(
            ["Version", "What changed"],
            migration_rows if migration_rows else [["—", "No migration comments found"]],
        )
    )


def page_assessment_cds():
    sections = parse_sections()
    alerts = parse_cds_alerts()
    algorithms = parse_cdss_algorithms()

    return (
        h(1, "Assessment &amp; CDS")
        + note(f"Parsed from source — {len(sections)} sections, {len(alerts)} CDS alerts, {len(algorithms)} CDSS algorithms. Auto-updates on every push.")
        + h(2, "3-step visit flow")
        + code(
            "Step 1 · Triage / Vitals\n"
            "  Vital signs · Chief complaints (UnifiedSymptomCatalog)\n\n"
            "Step 2 · Sectioned Assessment\n"
            "  Programme sections rendered by priority (SectionRegistry)\n"
            "  CDS banners fire as fields are filled\n"
            "  'Add pathway' actions activate new sections on the fly\n\n"
            "Step 3 · Summary & Submit\n"
            "  CDS alert review · Referral decision · Submit to upload queue",
            language="text",
        )
        + h(2, f"Section Registry ({len(sections)} sections)")
        + p("Parsed from <code>lib/features/visit/composer/section_registry.dart</code>. "
            "Add a <code>FormSection</code> here and it appears automatically in this table on the next push.")
        + table(
            ["Section ID", "Programmes", "Priority", "Fields"],
            [[sid, progs, str(prio), str(fcount)] for sid, progs, prio, fcount in sections],
        )
        + h(2, f"CDS Alert Rules ({len(alerts)} alerts)")
        + p("Parsed from <code>lib/features/visit/composer/cds_rules.dart</code>.")
        + table(
            ["Alert ID", "Severity", "Action"],
            [[aid, sev, act] for aid, sev, act in alerts],
        )
        + h(2, f"CDSS Algorithms ({len(algorithms)} calculators)")
        + p("Parsed from <code>lib/core/cdss/*_calculator.dart</code>.")
        + table(
            ["Class", "Trigger condition"],
            [[cls, trig] for cls, trig in algorithms],
        )
    )


def page_api_reference():
    return (
        h(1, "API Reference")
        + info(
            "All endpoints on <code>offline-service</code> via nginx :80. "
            "Auth: <code>Authorization: Bearer &lt;jwt&gt;</code>. "
            "Ground-truth: <code>lib/core/api/endpoints.dart</code> — never invent paths."
        )
        + h(2, "Auth")
        + table(
            ["Method", "Path", "Body", "Returns"],
            [["POST", "/offline-service/offline-sync/login", "multipart: username, password", "JWT in Authorization header"]],
        )
        + h(2, "Download (sync)")
        + table(
            ["Entity", "Method + Path", "Notes"],
            [
                ["Households", "GET /offline-service/offline-sync/household-list", ""],
                ["Members", "GET /offline-service/offline-sync/member-list", ""],
                ["Patients", "GET /offline-service/offline-sync/patient-list", ""],
                ["Assessment history", "GET /offline-service/offline-sync/member-assessment-history", "visitDate always present; nextFollowUpDate sparse"],
                ["Follow-ups", "GET /offline-service/offline-sync/follow-up-list", ""],
                ["Immunisations", "GET /offline-service/offline-sync/immunisation-list", ""],
                ["Referrals", "GET /offline-service/offline-sync/referral-list", ""],
            ],
        )
        + h(2, "Upload")
        + table(
            ["Entity", "Method + Path", "Body"],
            [["Assessment", "POST /offline-service/offline-sync/assessment-upload", "JSON assessment payload"]],
        )
        + h(2, "Notes")
        + ul([
            "All timestamps are epoch milliseconds.",
            "Warm sync uses <code>?updatedAt=&lt;epoch&gt;</code> query param.",
            "JWT expiry: re-login on 401.",
            "Never invent paths — verify against Java controllers and <code>lib/core/api/endpoints.dart</code>.",
        ])
    )


def page_changelog():
    try:
        raw = subprocess.check_output(
            ["git", "log", "--oneline", "-50", "--format=%H|%h|%s|%ai|%an"],
            text=True, cwd=REPO_ROOT,
        ).strip().split("\n")
    except subprocess.CalledProcessError:
        raw = []

    rows = []
    for line in raw:
        if not line:
            continue
        parts = line.split("|", 4)
        if len(parts) < 5:
            continue
        full_hash, short_hash, msg, date, author = parts
        link = (
            f'<a href="https://github.com/Medtronic-LABS/uhis_lf_mobile/commit/{full_hash}">'
            f"<code>{short_hash}</code></a>"
        )
        rows.append([link, msg, date[:10], author])

    return (
        h(1, "Changelog")
        + info(f"Auto-generated from git history. Last 50 commits. Updated: {TODAY}.")
        + (table(["Commit", "Message", "Date", "Author"], rows) if rows else p("No git history available."))
    )


# ---------------------------------------------------------------------------
# AI Service page builders
# Paths relative to the leapfrog-setup/ root (one level above REPO_ROOT).
# ---------------------------------------------------------------------------

_LF_ROOT = REPO_ROOT.parent  # leapfrog-setup/


def _read_py(rel: str) -> str:
    """Read a Python source file relative to leapfrog-setup/. Returns '' on missing."""
    path = _LF_ROOT / rel
    return path.read_text() if path.exists() else ""


def _parse_fastapi_routes(src: str) -> list[tuple[str, str, str, str]]:
    """
    Extract FastAPI route tuples (method, path, response_model, docstring)
    from source text using regex.
    Returns list of (METHOD, path, response_model, summary).
    """
    routes = []
    pattern = re.compile(
        r'@router\.(get|post|put|delete|patch)\s*\(\s*["\']([^"\']+)["\']'
        r'(?:[^)]*response_model\s*=\s*(\w+))?[^)]*\)'
        r'(?:\s*@[^\n]+\n)*'          # skip stacked decorators
        r'\s*(?:async\s+)?def\s+\w+[^:]*:'
        r'\s*"""([^"]*?)"""',
        re.DOTALL,
    )
    for m in pattern.finditer(src):
        method = m.group(1).upper()
        path = m.group(2)
        model = m.group(3) or "—"
        doc = m.group(4).strip().split("\n")[0].strip() if m.group(4) else "—"
        routes.append((method, path, model, doc))
    return routes


def _parse_pydantic_models(src: str) -> list[tuple[str, list[str]]]:
    """
    Extract Pydantic model names and their field names from source text.
    Returns list of (ModelName, [field: type, ...]).
    """
    models = []
    # Match class Foo(BaseModel): ... until next class or EOF
    class_pattern = re.compile(r'class\s+(\w+)\s*\((?:BaseModel|[A-Za-z]+Model)\)[^:]*:(.*?)(?=\nclass |\Z)', re.DOTALL)
    field_pattern = re.compile(r'^\s{4}(\w+)\s*:\s*([^\n=]+?)(?:\s*=.*)?$', re.MULTILINE)
    for cm in class_pattern.finditer(src):
        name = cm.group(1)
        body = cm.group(2)
        fields = [f"{fm.group(1)}: {fm.group(2).strip()}" for fm in field_pattern.finditer(body)]
        if fields:
            models.append((name, fields))
    return models


def _parse_settings(src: str) -> list[tuple[str, str, str]]:
    """
    Extract settings fields from a pydantic-settings class.
    Returns list of (field_name, type_hint, default).
    """
    settings = []
    field_pat = re.compile(r'^\s{4}(\w+)\s*:\s*([^\n=]+?)\s*=\s*(.+)$', re.MULTILINE)
    for m in field_pat.finditer(src):
        name = m.group(1)
        if name.startswith("model_"):
            continue
        settings.append((name.upper(), m.group(2).strip(), m.group(3).strip().strip('"').strip("'")))
    return settings


def page_ai_scribe():
    scribe_root = "ai-scribe-service/app"

    scribe_src   = _read_py(f"{scribe_root}/api/scribe.py")
    upload_src   = _read_py(f"{scribe_root}/api/upload.py")
    schemas_src  = _read_py(f"{scribe_root}/models/schemas.py")
    config_src   = _read_py(f"{scribe_root}/core/config.py")

    scribe_routes = _parse_fastapi_routes(scribe_src)
    upload_routes = _parse_fastapi_routes(upload_src)
    models        = _parse_pydantic_models(schemas_src)
    env_vars      = _parse_settings(config_src)

    scribe_rows = [
        [f"<code>{m}</code>", f"<code>/ai-scribe-service{p}</code>", f"<code>{r}</code>", d]
        for m, p, r, d in scribe_routes
    ]
    upload_rows = [
        [f"<code>{m}</code>", f"<code>/ai-scribe-service{p}</code>", f"<code>{r}</code>", d]
        for m, p, r, d in upload_routes
    ]

    model_html = ""
    for name, fields in models:
        model_html += h(3, name)
        model_html += ul([f"<code>{f}</code>" for f in fields])

    env_rows = [(f"<code>{n}</code>", t, d) for n, t, d in env_vars]

    async_flow = [
        "<strong>POST /scribe/transcribe</strong> — upload audio → 202 Accepted + jobId",
        "<strong>GET /scribe/results/{jobId}</strong> — poll until status = completed",
        "<strong>GET /scribe/notes/{noteId}</strong> — fetch full SOAP note + FHIR Bundle + rationale",
        "<strong>POST /scribe/notes/{noteId}/accept</strong> — SK confirms; edits logged",
        "<strong>POST /scribe/notes/{noteId}/reject</strong> — SK discards; reason logged",
    ]

    chunked_flow = [
        "<strong>POST /upload/init</strong> — create session → uploadId + chunk params",
        "<strong>PUT /upload/{id}/chunk/{n}</strong> — send 256 KB slice (any order, resumable)",
        "<strong>GET /upload/{id}/status</strong> — check progress + missing chunks",
        "<strong>POST /upload/{id}/complete</strong> — assemble → S3 → queue transcription job",
        "<strong>DELETE /upload/{id}</strong> — cancel session",
    ]

    return (
        h(1, "AI Scribe Service")
        + info(
            "Voice → SOAP note pipeline for offline-first community health workers. "
            "Transcribes audio using Gemini / OpenAI / Sarvam ASR, runs structured inference, "
            "builds a FHIR R4 Bundle, and waits for SK acceptance before committing. "
            "Migrations run automatically on container start via <code>entrypoint.sh</code>."
        )
        + table(
            ["Item", "Value"],
            [
                ["Language", "Python 3.12 · FastAPI · Gunicorn + Uvicorn workers"],
                ["Port", "8095"],
                ["Gateway prefix", "<code>/ai-scribe-service/</code>"],
                ["Database", "PostgreSQL 16 — schema <code>ai_scribe</code>"],
                ["Auth cache", "Redis 7"],
                ["Default ASR model", "<code>gemini-2.5-flash</code>"],
                ["Default inference model", "<code>gpt-4o-mini</code>"],
                ["Audio storage", "S3 — folder <code>scribe/</code>"],
                ["Last published", TODAY],
            ],
        )
        + h(2, "Async Transcription Flow")
        + p("Optimised for rural Android devices on 2G/3G. Audio &lt; 1 MB → direct POST. Audio ≥ 1 MB → chunked upload then complete.")
        + ul(async_flow)
        + h(2, "Chunked Upload Flow")
        + p("256 KB chunks, resumable, 24-hour session TTL. Designed for connectivity drops in rural Bangladesh.")
        + ul(chunked_flow)
        + h(2, "Scribe Endpoints")
        + (table(["Method", "Path (via gateway)", "Response model", "Summary"], scribe_rows)
           if scribe_rows else p("No routes parsed."))
        + h(2, "Upload Endpoints")
        + (table(["Method", "Path (via gateway)", "Response model", "Summary"], upload_rows)
           if upload_rows else p("No routes parsed."))
        + h(2, "Request / Response Models")
        + (model_html if model_html else p("No Pydantic models parsed."))
        + h(2, "Environment Variables")
        + (table(["Variable", "Type", "Default"], env_rows) if env_rows else p("No settings parsed."))
        + h(2, "Human-in-the-loop invariant")
        + warning(
            "A scribe note is a <strong>proposal</strong> until explicitly accepted by the SK. "
            "Every accept/reject action is logged with the rationale snapshot (modelVersion, asrProvider, "
            "llmModel, confidence, humanReviewRequired). Auto-commit is prohibited."
        )
        + h(2, "triageNotes — triage context pass-through")
        + p(
            "The <code>metadata.triageNotes</code> field (optional string) lets the SK app pass triage-screen "
            "symptom observations into the inference prompt. This improves clinical extraction accuracy when "
            "the SK has already noted key symptoms before recording."
        )
        + note("This page is auto-generated from ai-scribe-service/app/ source on every push to main.")
    )


def page_ai_visit_briefing():
    svc_root = "ai-visit-briefing-service/app"

    main_src    = _read_py(f"{svc_root}/main.py")
    models_src  = _read_py(f"{svc_root}/models.py")
    gemini_src  = _read_py(f"{svc_root}/services/gemini_service.py")

    routes = _parse_fastapi_routes(main_src)
    models = _parse_pydantic_models(models_src)

    route_rows = [
        [f"<code>{m}</code>", f"<code>/ai-visit-briefing-service{p}</code>", f"<code>{r}</code>", d]
        for m, p, r, d in routes
    ]

    model_html = ""
    for name, fields in models:
        model_html += h(3, name)
        model_html += ul([f"<code>{f}</code>" for f in fields])

    # Parse Gemini model constant from gemini_service.py
    gemini_model = "gemini-2.5-flash"
    m = re.search(r'gemini[_-][\w.-]+', gemini_src)
    if m:
        gemini_model = m.group(0).replace("_", "-")

    cards = [
        ["Before You Knock", "<code>briefingCard</code>", "AI headline + 3-5 clinical bullet points (most important concern first)"],
        ["Today's Priorities", "<code>todaysPriorities</code>", "Numbered list of 3-5 actionable visit priorities with clinical specifics"],
        ["Suggested Discussion Points", "<code>suggestedDiscussionPoints</code>", "Culturally appropriate opening line + topic sections (heart / baby / nutrition / medication / lungs / home / checkup) each with 2-3 open-ended questions"],
    ]

    briefing_request_fields = [
        ["patientId", "Required — used for logging"],
        ["activeProgrammes", "Drives which topics appear in Discussion Points"],
        ["gestationalWeeks", "Triggers pregnancy-specific priorities"],
        ["recentVitals", "BP / glucose / weight snapshot → referenced in Today's Priorities"],
        ["openFollowUps", "Overdue follow-ups surfaced in Before You Knock"],
        ["riskIndicators", "Clinical risk tags → headline severity"],
        ["currentMedications", "Drug adherence check in Discussion Points"],
    ]

    return (
        h(1, "AI Visit Briefing Service")
        + info(
            "Generates three pre-visit AI briefing cards for the SK before each patient encounter. "
            "Cards are fetched asynchronously while the SK reviews symptoms on the triage screen. "
            "Powered by Gemini " + gemini_model + "."
        )
        + table(
            ["Item", "Value"],
            [
                ["Language", "Python 3.12 · FastAPI"],
                ["Port", "8096"],
                ["Gateway prefix", "<code>/ai-visit-briefing-service/</code>"],
                ["Direct dev URL", "<code>--dart-define=AI_SERVICE_URL=http://10.0.2.2:8096</code>"],
                ["AI model", f"<code>{gemini_model}</code>"],
                ["Auth", "None (internal service; gateway handles auth)"],
                ["Last published", TODAY],
            ],
        )
        + h(2, "Three Briefing Cards")
        + table(["Card", "Response field", "Content"], cards)
        + h(2, "Endpoints")
        + (table(["Method", "Path (via gateway)", "Response model", "Summary"], route_rows)
           if route_rows else p("No routes parsed."))
        + h(2, "BriefingRequest — key fields")
        + table(["Field", "Purpose"], briefing_request_fields)
        + h(2, "Request / Response Models")
        + (model_html if model_html else p("No Pydantic models parsed."))
        + h(2, "Flutter integration")
        + p(
            "Called from <code>VisitBriefingRepository</code> in <code>lib/features/visit/briefing/</code>. "
            "Fetch starts immediately after <code>PatientContext</code> is built in <code>SymptomPickerScreen</code>. "
            "Cards update when data arrives; a loading skeleton is shown during the fetch. "
            "Graceful degradation: Card 1 falls back to rule-based context chips; Cards 2 &amp; 3 show "
            "&#34;AI unavailable&#34; when the service is unreachable."
        )
        + h(2, "Graceful degradation")
        + ul([
            "Card 1 (Before You Knock) falls back to local rule-based context chips.",
            "Cards 2 &amp; 3 (Priorities + Discussion) show &#34;AI unavailable&#34; — visit proceeds normally.",
            "No crash, no blocked flow — offline-first contract maintained.",
        ])
        + note("This page is auto-generated from ai-visit-briefing-service/app/ source on every push to main.")
    )


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------
PAGES = [
    ("UHIS Leapfrog Mobile",       page_home),
    ("Developer Setup Guide",      page_developer_setup),
    ("Architecture Overview",      page_architecture),
    ("Screens & Navigation",       page_screens),
    ("Offline Sync Model",         page_offline_sync),
    ("Database Schema",            page_database),
    ("Assessment & CDS",           page_assessment_cds),
    ("API Reference",              page_api_reference),
    ("AI Scribe Service",          page_ai_scribe),
    ("AI Visit Briefing Service",  page_ai_visit_briefing),
    ("Changelog",                  page_changelog),
]

if __name__ == "__main__":
    print(f"Parsing source from: {REPO_ROOT}")
    print(f"Publishing {len(PAGES)} pages → {BASE_URL} (space: {SPACE}, parent: {PARENT_ID})\n")
    errors = []
    for title, builder in PAGES:
        try:
            upsert(title, builder())
        except Exception as exc:
            print(f"  ✗ error → {title}: {exc}", file=sys.stderr)
            errors.append(title)
    if errors:
        print(f"\nFailed: {errors}", file=sys.stderr)
        sys.exit(1)
    print(f"\nDone — {len(PAGES)} pages published.")
